#,Feature,TestCase,Result,ResultType,ExecutedOn,Description,Function,Module,Devices,KnownIssue
1,Regression,FtOpSoSwLagFn042,Pass,Mapped,2023-12-30 01:12:56,Test case passed,test_ft_portchannel_with_vlan_variations,switching/test_portchannel.py,"V3, V4",
2,Regression,FtOpSoSwLagFn041,Pass,Mapped,2023-12-30 01:12:56,Test case passed,test_ft_portchannel_with_vlan_variations,switching/test_portchannel.py,"V3, V4",
3,PortChannel Config Enhancements,FtOpSoSwPominFn007,Pass,Mapped,2023-12-30 01:13:20,Test case passed,test_ft_verify_min_links_functionality_by_flapping_all_member_ports_007,switching/test_portchannel.py,"V3, V4",
4,Regression,ft_lldp_LocManAddrLen,Fail,Mapped,2023-12-30 01:20:17,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_LocManAddrLen,system/test_lldp.py,"V3, V4",
5,Regression,ft_lldp_LocManAddrlfld,Fail,Mapped,2023-12-30 01:20:18,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_LocManAddrlfld,system/test_lldp.py,"V3, V4",
6,Regression,ft_lldp_LocManAddrEntry,Fail,Mapped,2023-12-30 01:20:18,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_LocManAddrEntry,system/test_lldp.py,"V3, V4",
7,Regression,ft_lldp_ConfigManAddrEntry,Fail,Mapped,2023-12-30 01:20:19,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_ConfigManAddrEntry,system/test_lldp.py,"V3, V4",
8,Regression,ft_lldp_lldplocportid,Fail,Mapped,2023-12-30 01:20:19,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_lldplocportid,system/test_lldp.py,"V3, V4",
9,Regression,ft_lldp_lldplocsysname,Fail,Mapped,2023-12-30 01:20:19,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_lldplocsysname,system/test_lldp.py,"V3, V4",
10,Regression,ft_lldp_lldplocsysdesc,Fail,Mapped,2023-12-30 01:20:20,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_lldplocsysdesc,system/test_lldp.py,"V3, V4",
11,SNMP Agent Optimization,ft_snmp_lldp_prem_manaddr_table,Fail,Mapped,2023-12-30 01:20:20,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_rem_man_addr_table,system/test_lldp.py,"V3, V4",
12,Regression,FtOpSoSwlldpFn011,Fail,Mapped,2023-12-30 01:20:20,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_non_default_config,system/test_lldp.py,"V3, V4",
13,Regression,FtOpSoSwlldpFn010,Fail,Mapped,2023-12-30 01:20:20,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_non_default_config,system/test_lldp.py,"V3, V4",
14,Regression,FtOpSoSwlldpFn009,Fail,Mapped,2023-12-30 01:20:20,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_non_default_config,system/test_lldp.py,"V3, V4",
15,Regression,FtOpSoSwlldpFn008,Fail,Mapped,2023-12-30 01:20:20,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_non_default_config,system/test_lldp.py,"V3, V4",
16,Regression,FtOpSoSwlldpFn004,Fail,Mapped,2023-12-30 01:20:20,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_non_default_config,system/test_lldp.py,"V3, V4",
17,Regression,FtOpSoSwlldpFn013,Fail,Mapped,2023-12-30 01:20:21,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_docker_restart,system/test_lldp.py,"V3, V4",
18,Regression,lldp_verify_counters,Fail,Mapped,2023-12-30 01:20:21,module configuration failed. LLDP neighbors information is not found after polling @5445,test_lldp_verify_counters,system/test_lldp.py,"V3, V4",
19,Regression,ft_lldp_with_remote_server,Fail,Mapped,2023-12-30 01:20:22,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_with_remote_server,system/test_lldp.py,"V3, V4",
20,Regression,ft_ssh_service_disable,Pass,Mapped,2023-12-30 01:26:03,Test case passed,test_ft_ssh_service_disable,system/test_ssh.py,"V3, V4",
21,Regression,ft_ssh_add_user_verify,Fail,Mapped,2023-12-30 01:36:32,Test case Failed.,test_ft_ssh_add_user_verify,system/test_ssh.py,"V3, V4",
22,Control Plane ACL,test_ft_controlplane_acl_service_sshv4,Pass,SubTest,2023-12-30 01:36:32,SSH failed,test_ft_ssh_add_user_verify,system/test_ssh.py,"V3, V4",
23,Control Plane ACL,test_ft_controlplane_acl_service_sshv6,Pass,SubTest,2023-12-30 01:36:32,SSH failed,test_ft_ssh_add_user_verify,system/test_ssh.py,"V3, V4",
24,Control Plane ACL,test_ft_controlplane_acl_service_snmp,Fail,SubTest,2023-12-30 01:36:32,SNMP output is not found after walk of with control plane ACL service SNMP after reboot OID,test_ft_ssh_add_user_verify,system/test_ssh.py,"V3, V4",
25,Regression,CETA_SONIC_67575,Pass,Mapped,2023-12-30 01:36:58,Test case passed,test_ft_verify_logs_at_the_time_of_ssh_login_success,system/test_ssh.py,"V3, V4",
