#,Node,Module,Function,Result,Test Time,Helper Time,CMD Time,TG Time,Wait,TGWait,PROMPT NFOUND,TECH SUPPORT,Description
1,gw4,system/test_snapshot.py,test_ft_watermark_telemetry_interval,,0:00:53,0:00:00.000,0:00:10.183,0:00:00.000,0:00:00,0:00:00,0,0,Module Configuration
2,gw4,system/test_snapshot.py,test_ft_watermark_telemetry_interval,Pass,0:00:15,0:00:00.000,0:00:07.810,0:00:00.000,0:00:00,0:00:00,0,0,verification of configured telemetry interval and reset to default interval is successful
3,gw4,system/test_snmp.py,test_ft_snmp_sysName,,0:02:09,0:00:18.246,0:00:37.757,0:00:00.000,0:00:02,0:00:00,0,0,Module Configuration
4,gw4,system/test_snmp.py,test_ft_snmp_sysName,Fail,0:00:06,0:00:00.000,0:00:00.258,0:00:00.000,0:00:00,0:00:00,0,0,sysname output is not in sync between system and snmp
5,gw4,system/test_snmp.py,test_ft_snmp_test_syUpTime,Pass,0:00:06,0:00:00.000,0:00:00.663,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
6,gw4,system/test_snmp.py,test_ft_snmp_sysDescr,Pass,0:00:08,0:00:00.000,0:00:01.400,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
7,gw4,system/test_snmp.py,test_ft_snmp_mib_2,Pass,0:00:11,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
8,gw4,system/test_snmp.py,test_ft_snmp_if_mib_all,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
9,gw4,system/test_snmp.py,test_ft_snmp_entity_mib_all,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
10,gw4,system/test_snmp.py,test_ft_snmp_dot1q_dot1db_mib,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
11,gw4,system/test_snmp.py,test_ft_snmp_root_node_walk,Pass,0:00:16,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
12,gw4,system/test_snmp.py,test_ft_snmp_ipAddressRowStatus_ipv6,Pass,0:00:11,0:00:00.000,0:00:02.498,0:00:00.000,0:00:02,0:00:00,0,0,Test case passed
13,gw4,system/test_snmp.py,test_ft_snmp_ipAddressStorageType_ipv6,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
14,gw4,system/test_snmp.py,test_ft_snmp_ipv6_If_Forward_default_HopLimit,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
15,gw4,system/test_snmp.py,test_ft_snmp_ipv6scope_index_table,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
16,gw4,system/test_snmp.py,test_ft_snmp_ip_forward_table,Pass,0:00:08,0:00:00.000,0:00:01.241,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
17,gw4,system/test_snmp.py,test_ft_snmp_ifx_table,Pass,0:00:06,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
18,gw4,system/test_snmp.py,test_ft_snmp_ip_System_Stats_Table,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
19,gw4,system/test_snmp.py,test_ft_snmp_ip_IfStats_Table,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
20,gw4,system/test_snmp.py,test_ft_snmp_ip_Address_Table,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
21,gw4,system/test_snmp.py,test_ft_snmp_ip_NetToPhysical_Table,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
22,gw4,system/test_snmp.py,test_ft_snmp_icmp_Msgs,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
23,gw4,system/test_snmp.py,test_ft_snmp_tcp_mib,Pass,0:00:20,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
24,gw4,system/test_snmp.py,test_ft_snmp_udp_mib,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
25,gw4,system/test_snmp.py,test_ft_snmp_snmpv2_mib,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
26,gw4,system/test_snmp.py,test_ft_snmp_host_resource_mib,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
27,gw4,system/test_snmp.py,test_ft_snmp_framework_mib,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
28,gw4,system/test_snmp.py,test_ft_snmp_mpd_mib,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
29,gw4,system/test_snmp.py,test_ft_snmp_target_mib,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
30,gw4,system/test_snmp.py,test_ft_snmp_notification_mib,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
31,gw4,system/test_snmp.py,test_ft_snmp_user_based_sm_mib,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
32,gw4,system/test_snmp.py,test_ft_snmp_view_based_acm_mib,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
33,gw4,system/test_snmp.py,test_ft_snmp_ent_physical_table,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
34,gw4,system/test_snmp.py,test_ft_snmp_dot3_stats_table,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
35,gw4,system/test_snmp.py,test_ft_net_snmp_agent_mib,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
36,gw4,system/test_snmp.py,test_ft_net_snmp_vacm_mib,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
37,gw4,system/test_snmp.py,test_ft_snmp_ucd_diskio_mib,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
38,gw4,system/test_snmp.py,test_ft_snmp_ucd_la_table,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
39,gw4,system/test_snmp.py,test_ft_snmp_ucd_system_stats,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
40,gw4,system/test_snmp.py,test_ft_snmp_dot1q_tp_fdb_port,Fail,0:00:07,0:00:00.000,0:00:00.766,0:00:00.000,0:00:00,0:00:00,0,0,SNMP output is not found after walk of dot1qTpFdbPort OID
41,gw4,system/test_snmp.py,test_ft_snmp_dot1q_tp_fdb_address,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
42,gw4,system/test_snmp.py,test_ft_snmp_coldstart_trap,EnvFail,0:00:19,0:00:00.000,0:00:00.000,0:00:00.000,0:00:09,0:00:00,0,0,Test case Failed Couldn't get the snmptrapd process details from snmp trap server. Please check the snmp trap server process in the server.
43,gw4,system/test_snmp.py,test_ft_snmp_docker_restart,Fail,0:00:17,0:00:00.000,0:00:09.846,0:00:00.000,0:00:00,0:00:00,0,0,SNMP service is not up
44,gw7,system/test_ntp.py,test_ft_ntp_disable_enable_with_message_log,,0:00:28,0:00:00.000,0:00:05.495,0:00:00.000,0:00:00,0:00:00,0,0,Module Configuration
45,gw7,system/test_ntp.py,test_ft_ntp_disable_enable_with_message_log,Pass,0:05:07,0:00:00.000,0:01:16.973,0:00:00.000,0:02:16,0:00:00,0,0,Test case passed
46,gw7,system/test_ntp.py,test_ntp_exists_config,Pass,0:00:11,0:00:00.000,0:00:04.077,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
47,gw7,security/test_tacacs.py,test_ft_tacacs_ssh_login_with_tacacs_operations,,0:00:57,0:00:17.046,0:00:10.953,0:00:00.000,0:00:00,0:00:00,0,0,Module Configuration
48,gw7,security/test_tacacs.py,test_ft_tacacs_ssh_login_with_tacacs_operations,Fail,0:00:06,0:00:00.000,0:00:00.260,0:00:00.000,0:00:00,0:00:00,0,0,PAM file is not created
49,gw2,switching/test_portchannel.py,test_ft_portchannel_with_vlan_variations,,0:00:48,0:00:00.000,0:00:20.918,0:00:00.000,0:00:00,0:00:00,0,0,Module Configuration
50,gw2,switching/test_portchannel.py,test_ft_portchannel_with_vlan_variations,Fail,0:01:51,0:00:00.000,0:00:57.287,0:00:00.000,0:01:48,0:00:00,0,0,Portchannel PortChannel7 on V4 with member ['Ethernet48'  'Ethernet52'] verification failed
51,gw2,switching/test_portchannel.py,test_ft_verify_min_links_functionality_by_flapping_all_member_ports_007,ConfigFail,0:00:39,0:00:00.000,0:00:19.952,0:00:00.000,0:00:00,0:00:00,0,0,pre-test configuration failed Invalid error code PortChannel Verification Failed : unknown message identifier 'PortChannel Verification Failed' @5430
52,gw2,system/test_interface.py,test_ft_port_fn_verify_shut_noshut,,0:01:13,0:00:36.534,0:00:21.237,0:00:00.000,0:00:00,0:00:00,0,0,Module Configuration
53,gw2,system/test_interface.py,test_ft_port_fn_verify_shut_noshut,DUTFail,0:00:49,0:00:21.839,0:00:14.033,0:00:00.000,0:00:00,0:00:00,0,0,config command 'sudo -s config interface ip remove Ethernet48 11.11.11.11/24' failed
54,gw2,system/test_ssh.py,test_ft_ssh_service_disable,,0:01:52,0:01:01.755,0:00:28.489,0:00:00.000,0:00:10,0:00:00,0,0,Module Configuration
55,gw2,system/test_ssh.py,test_ft_ssh_service_disable,Pass,0:00:08,0:00:00.000,0:00:00.670,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
56,gw2,system/test_ssh.py,test_ft_ssh_add_user_verify,Fail,0:09:09,0:00:00.000,0:03:48.246,0:00:00.000,0:00:03,0:00:00,0,0,Test case Failed.
57,gw2,system/test_ssh.py,test_ft_verify_logs_at_the_time_of_ssh_login_success,Pass,0:00:22,0:00:00.000,0:00:05.412,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
58,gw3,switching/test_vlan.py,test_ft_add_unknownvlan_interface,,0:00:39,0:00:00.000,0:00:14.140,0:00:00.000,0:00:00,0:00:00,0,0,Module Configuration
59,gw3,switching/test_vlan.py,test_ft_add_unknownvlan_interface,Pass,0:00:09,0:00:00.000,0:00:01.843,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
60,gw3,switching/test_vlan.py,test_ft_vlan_delete_with_member,Pass,0:00:13,0:00:00.000,0:00:04.397,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
61,gw3,switching/test_vlan.py,test_ft_vlan_trunk_tagged,Pass,0:01:26,0:00:00.000,0:00:01.982,0:00:00.000,0:00:15,0:00:20,0,0,Test case passed
62,gw3,switching/test_vlan.py,test_ft_vlan_save_config_warm_and_fast_reboot,ScriptError,0:05:14,0:01:56.025,0:01:49.746,0:00:00.000,0:00:10,0:00:00,0,0,Exception TypeError 'NoneType' object is not subscriptable in file /apis/system/basic.py at line 1389
63,gw3,system/test_lldp.py,test_ft_lldp_LocManAddrLen,Fail,0:00:00,0:00:49.720,0:00:54.398,0:00:00.000,0:00:40,0:00:00,0,0,module configuration failed. LLDP neighbors information is not found after polling @5445
64,gw3,system/test_lldp.py,test_ft_lldp_LocManAddrlfld,Fail,0:00:00,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,module configuration failed. LLDP neighbors information is not found after polling @5445
65,gw3,system/test_lldp.py,test_ft_lldp_LocManAddrEntry,Fail,0:00:00,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,module configuration failed. LLDP neighbors information is not found after polling @5445
66,gw3,system/test_lldp.py,test_ft_lldp_ConfigManAddrEntry,Fail,0:00:00,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,module configuration failed. LLDP neighbors information is not found after polling @5445
67,gw3,system/test_lldp.py,test_ft_lldp_lldplocportid,Fail,0:00:00,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,module configuration failed. LLDP neighbors information is not found after polling @5445
68,gw3,system/test_lldp.py,test_ft_lldp_lldplocsysname,Fail,0:00:00,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,module configuration failed. LLDP neighbors information is not found after polling @5445
69,gw3,system/test_lldp.py,test_ft_lldp_lldplocsysdesc,Fail,0:00:00,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,module configuration failed. LLDP neighbors information is not found after polling @5445
70,gw3,system/test_lldp.py,test_ft_lldp_rem_man_addr_table,Fail,0:00:00,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,module configuration failed. LLDP neighbors information is not found after polling @5445
71,gw3,system/test_lldp.py,test_ft_lldp_non_default_config,Fail,0:00:00,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,module configuration failed. LLDP neighbors information is not found after polling @5445
72,gw3,system/test_lldp.py,test_ft_lldp_docker_restart,Fail,0:00:00,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,module configuration failed. LLDP neighbors information is not found after polling @5445
73,gw3,system/test_lldp.py,test_lldp_verify_counters,Fail,0:00:00,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,module configuration failed. LLDP neighbors information is not found after polling @5445
74,gw3,system/test_lldp.py,test_ft_lldp_with_remote_server,Fail,0:00:00,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,module configuration failed. LLDP neighbors information is not found after polling @5445
