#,Node,Module,Function,Result,Test Time,Helper Time,CMD Time,TG Time,Wait,TGWait,PROMPT NFOUND,TECH SUPPORT,Description
1,gw4,system/test_snapshot.py,test_ft_watermark_telemetry_interval,,0:00:53,0:00:00.000,0:00:10.297,0:00:00.000,0:00:00,0:00:00,0,0,Module Configuration
2,gw4,system/test_snapshot.py,test_ft_watermark_telemetry_interval,Pass,0:00:15,0:00:00.000,0:00:07.920,0:00:00.000,0:00:00,0:00:00,0,0,verification of configured telemetry interval and reset to default interval is successful
3,gw4,security/test_tacacs.py,test_ft_tacacs_ssh_login_with_tacacs_operations,,0:00:59,0:00:18.244,0:00:11.058,0:00:00.000,0:00:00,0:00:00,0,0,Module Configuration
4,gw4,security/test_tacacs.py,test_ft_tacacs_ssh_login_with_tacacs_operations,Fail,0:00:06,0:00:00.000,0:00:00.270,0:00:00.000,0:00:00,0:00:00,0,0,PAM file is not created
5,gw5,system/test_snmp.py,test_ft_snmp_sysName,,0:01:43,0:00:00.000,0:00:34.840,0:00:00.000,0:00:02,0:00:00,0,0,Module Configuration
6,gw5,system/test_snmp.py,test_ft_snmp_sysName,Fail,0:00:06,0:00:00.000,0:00:00.258,0:00:00.000,0:00:00,0:00:00,0,0,sysname output is not in sync between system and snmp
7,gw5,system/test_snmp.py,test_ft_snmp_test_syUpTime,Pass,0:00:06,0:00:00.000,0:00:00.663,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
8,gw5,system/test_snmp.py,test_ft_snmp_sysDescr,Pass,0:00:08,0:00:00.000,0:00:01.395,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
9,gw5,system/test_snmp.py,test_ft_snmp_mib_2,Pass,0:00:11,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
10,gw5,system/test_snmp.py,test_ft_snmp_if_mib_all,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
11,gw5,system/test_snmp.py,test_ft_snmp_entity_mib_all,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
12,gw5,system/test_snmp.py,test_ft_snmp_dot1q_dot1db_mib,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
13,gw5,system/test_snmp.py,test_ft_snmp_root_node_walk,Pass,0:00:17,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
14,gw5,system/test_snmp.py,test_ft_snmp_ipAddressRowStatus_ipv6,Pass,0:00:11,0:00:00.000,0:00:02.502,0:00:00.000,0:00:02,0:00:00,0,0,Test case passed
15,gw5,system/test_snmp.py,test_ft_snmp_ipAddressStorageType_ipv6,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
16,gw5,system/test_snmp.py,test_ft_snmp_ipv6_If_Forward_default_HopLimit,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
17,gw5,system/test_snmp.py,test_ft_snmp_ipv6scope_index_table,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
18,gw5,system/test_snmp.py,test_ft_snmp_ip_forward_table,Pass,0:00:08,0:00:00.000,0:00:01.237,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
19,gw5,system/test_snmp.py,test_ft_snmp_ifx_table,Pass,0:00:06,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
20,gw5,system/test_snmp.py,test_ft_snmp_ip_System_Stats_Table,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
21,gw5,system/test_snmp.py,test_ft_snmp_ip_IfStats_Table,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
22,gw5,system/test_snmp.py,test_ft_snmp_ip_Address_Table,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
23,gw5,system/test_snmp.py,test_ft_snmp_ip_NetToPhysical_Table,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
24,gw5,system/test_snmp.py,test_ft_snmp_icmp_Msgs,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
25,gw5,system/test_snmp.py,test_ft_snmp_tcp_mib,Pass,0:00:20,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
26,gw5,system/test_snmp.py,test_ft_snmp_udp_mib,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
27,gw5,system/test_snmp.py,test_ft_snmp_snmpv2_mib,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
28,gw5,system/test_snmp.py,test_ft_snmp_host_resource_mib,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
29,gw5,system/test_snmp.py,test_ft_snmp_framework_mib,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
30,gw5,system/test_snmp.py,test_ft_snmp_mpd_mib,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
31,gw5,system/test_snmp.py,test_ft_snmp_target_mib,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
32,gw5,system/test_snmp.py,test_ft_snmp_notification_mib,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
33,gw5,system/test_snmp.py,test_ft_snmp_user_based_sm_mib,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
34,gw5,system/test_snmp.py,test_ft_snmp_view_based_acm_mib,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
35,gw5,system/test_snmp.py,test_ft_snmp_ent_physical_table,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
36,gw5,system/test_snmp.py,test_ft_snmp_dot3_stats_table,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
37,gw5,system/test_snmp.py,test_ft_net_snmp_agent_mib,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
38,gw5,system/test_snmp.py,test_ft_net_snmp_vacm_mib,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
39,gw5,system/test_snmp.py,test_ft_snmp_ucd_diskio_mib,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
40,gw5,system/test_snmp.py,test_ft_snmp_ucd_la_table,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
41,gw5,system/test_snmp.py,test_ft_snmp_ucd_system_stats,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
42,gw5,system/test_snmp.py,test_ft_snmp_dot1q_tp_fdb_port,Fail,0:00:07,0:00:00.000,0:00:00.770,0:00:00.000,0:00:00,0:00:00,0,0,SNMP output is not found after walk of dot1qTpFdbPort OID
43,gw5,system/test_snmp.py,test_ft_snmp_dot1q_tp_fdb_address,Pass,0:00:05,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
44,gw5,system/test_snmp.py,test_ft_snmp_coldstart_trap,EnvFail,0:00:19,0:00:00.000,0:00:00.000,0:00:00.000,0:00:09,0:00:00,0,0,Test case Failed Couldn't get the snmptrapd process details from snmp trap server. Please check the snmp trap server process in the server.
45,gw5,system/test_snmp.py,test_ft_snmp_docker_restart,Fail,0:00:20,0:00:00.000,0:00:11.464,0:00:00.000,0:00:00,0:00:00,0,0,sysname output is not in sync between system and snmp after docker restart
46,gw6,system/test_ntp.py,test_ft_ntp_disable_enable_with_message_log,,0:00:28,0:00:00.000,0:00:05.390,0:00:00.000,0:00:00,0:00:00,0,0,Module Configuration
47,gw6,system/test_ntp.py,test_ft_ntp_disable_enable_with_message_log,Pass,0:05:08,0:00:00.000,0:01:17.338,0:00:00.000,0:02:16,0:00:00,0,0,Test case passed
48,gw6,system/test_ntp.py,test_ntp_exists_config,Pass,0:00:11,0:00:00.000,0:00:04.074,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
49,gw2,switching/test_portchannel.py,test_ft_portchannel_with_vlan_variations,,0:00:48,0:00:00.000,0:00:21.195,0:00:00.000,0:00:00,0:00:00,0,0,Module Configuration
50,gw2,switching/test_portchannel.py,test_ft_portchannel_with_vlan_variations,Fail,0:01:52,0:00:00.000,0:00:59.031,0:00:00.000,0:01:48,0:00:00,0,0,Portchannel PortChannel7 on V4 with member ['Ethernet48'  'Ethernet52'] verification failed
51,gw2,switching/test_portchannel.py,test_ft_verify_min_links_functionality_by_flapping_all_member_ports_007,ConfigFail,0:00:40,0:00:00.000,0:00:20.877,0:00:00.000,0:00:00,0:00:00,0,0,pre-test configuration failed Invalid error code PortChannel Verification Failed : unknown message identifier 'PortChannel Verification Failed' @5430
52,gw2,system/test_ssh.py,test_ft_ssh_service_disable,,0:01:10,0:00:36.493,0:00:23.119,0:00:00.000,0:00:00,0:00:00,0,0,Module Configuration
53,gw2,system/test_ssh.py,test_ft_ssh_service_disable,Pass,0:00:08,0:00:00.000,0:00:00.671,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
54,gw2,system/test_ssh.py,test_ft_ssh_add_user_verify,Fail,0:09:15,0:00:00.000,0:03:52.346,0:00:00.000,0:00:03,0:00:00,0,0,Test case Failed.
55,gw2,system/test_ssh.py,test_ft_verify_logs_at_the_time_of_ssh_login_success,Pass,0:00:21,0:00:00.000,0:00:05.310,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
56,gw3,switching/test_vlan.py,test_ft_add_unknownvlan_interface,,0:00:39,0:00:00.000,0:00:13.899,0:00:00.000,0:00:00,0:00:00,0,0,Module Configuration
57,gw3,switching/test_vlan.py,test_ft_add_unknownvlan_interface,Pass,0:00:08,0:00:00.000,0:00:01.788,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
58,gw3,switching/test_vlan.py,test_ft_vlan_delete_with_member,Pass,0:00:13,0:00:00.000,0:00:04.389,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
59,gw3,switching/test_vlan.py,test_ft_vlan_trunk_tagged,Pass,0:01:26,0:00:00.000,0:00:01.832,0:00:00.000,0:00:15,0:00:20,0,0,Test case passed
60,gw3,switching/test_vlan.py,test_ft_vlan_save_config_warm_and_fast_reboot,ScriptError,0:05:13,0:01:53.614,0:01:51.175,0:00:00.000,0:00:10,0:00:00,0,0,Exception TypeError 'NoneType' object is not subscriptable in file /apis/system/basic.py at line 1389
61,gw3,system/test_interface.py,test_ft_port_fn_verify_shut_noshut,,0:01:42,0:00:53.329,0:00:25.843,0:00:00.000,0:00:10,0:00:00,0,0,Module Configuration
62,gw3,system/test_interface.py,test_ft_port_fn_verify_shut_noshut,Fail,0:01:16,0:00:21.836,0:00:27.506,0:00:00.000,0:00:00,0:00:00,0,0,interface is down on DUT ['Ethernet16']
63,gw3,system/test_lldp.py,test_ft_lldp_LocManAddrLen,Fail,0:00:00,0:01:29.377,0:00:54.377,0:00:00.000,0:00:40,0:00:00,0,0,module configuration failed. LLDP neighbors information is not found after polling @5445
64,gw3,system/test_lldp.py,test_ft_lldp_LocManAddrlfld,Fail,0:00:00,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,module configuration failed. LLDP neighbors information is not found after polling @5445
65,gw3,system/test_lldp.py,test_ft_lldp_LocManAddrEntry,Fail,0:00:00,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,module configuration failed. LLDP neighbors information is not found after polling @5445
66,gw3,system/test_lldp.py,test_ft_lldp_ConfigManAddrEntry,Fail,0:00:00,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,module configuration failed. LLDP neighbors information is not found after polling @5445
67,gw3,system/test_lldp.py,test_ft_lldp_lldplocportid,Fail,0:00:00,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,module configuration failed. LLDP neighbors information is not found after polling @5445
68,gw3,system/test_lldp.py,test_ft_lldp_lldplocsysname,Fail,0:00:00,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,module configuration failed. LLDP neighbors information is not found after polling @5445
69,gw3,system/test_lldp.py,test_ft_lldp_lldplocsysdesc,Fail,0:00:00,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,module configuration failed. LLDP neighbors information is not found after polling @5445
70,gw3,system/test_lldp.py,test_ft_lldp_rem_man_addr_table,Fail,0:00:00,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,module configuration failed. LLDP neighbors information is not found after polling @5445
71,gw3,system/test_lldp.py,test_ft_lldp_non_default_config,Fail,0:00:00,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,module configuration failed. LLDP neighbors information is not found after polling @5445
72,gw3,system/test_lldp.py,test_ft_lldp_docker_restart,Fail,0:00:00,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,module configuration failed. LLDP neighbors information is not found after polling @5445
73,gw3,system/test_lldp.py,test_lldp_verify_counters,Fail,0:00:00,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,module configuration failed. LLDP neighbors information is not found after polling @5445
74,gw3,system/test_lldp.py,test_ft_lldp_with_remote_server,Fail,0:00:00,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,module configuration failed. LLDP neighbors information is not found after polling @5445
