2024-01-06 00:50:25,933 T0000: NOTICE WORKER = gw1
2024-01-06 00:50:25,933 T0000: NOTICE using testbed file /data/work/logs/docker-master-448374-l3/testbed_1_4_1.yaml
2024-01-06 00:50:25,933 T0000: NOTICE Execution Start Time: 2024-01-06 00:50:25.932253
2024-01-06 00:50:25,933 T0000: NOTICE LOGS PATH: /data/work/logs/docker-master-448374-l3/gw1
2024-01-06 00:50:26,446 T0000: NOTICE VERSION: UNKNOWN UNKNOWN UNKNOWN
2024-01-06 00:50:26,447 T0000: NOTICE HOST: sonicmgmtmaster MEM: 376gb 53.0%
2024-01-06 00:50:26,447 T0000: NOTICE ROOT_PATH: /repo
2024-01-06 00:50:26,447 T0000: NOTICE Python: 3.8.10
2024-01-06 00:50:26,447 T0000: NOTICE Topology unknown: D1T1:4,D1D2:6,D1D3:4,D1D4:4,D2T1:4,D2D3:4,D2D4:4,D3T1:4,D3D4:6,D4T1:4
2024-01-06 00:50:26,447 T0000: DEBUG 
SUITE ARGS: --load-image none --max-time module 9000 --max-time function 5400 --max-time session 3600 --logs-level=debug --topology-check=function --env SPYTEST_TESTBED_IGNORE_CONSTRAINTS TG,TGCARD,TGSPEED,CHIP,MODEL --noop --env SPYTEST_RESET_CONSOLES 0 --noop --env SPYTEST_ONREBOOT_RENEW_MGMT_IP 1 --noop --env SPYTEST_RECOVERY_CR_PER_CMD_POST_OP 1 --noop --env SPYTEST_BATCH_POLL_STATUS_TIME 300 --noop --env SPYTEST_BATCH_DEAD_NODE_MAX_TIME 7200 --noop --breakout-mode none --env SPYTEST_SHUTDOWN_FREE_PORTS 1 --env SPYTEST_HOOKS_BREAKOUT_UITYPE click --env SPYTEST_ONREBOOT_RENEW_MGMT_IP 0 --env SPYTEST_VERIFY_CSV_MIN_TOPOLOGY 1 --env SPYTEST_CMD_FAIL_RESULT_SUPPORT 0 --env SPYTEST_ROUTING_CONFIG_MODE split --env SPYTEST_CLEAR_DEVICE_METADATA_BGP_ASN 1 --env SPYTEST_TEXTFSM_USE_BUNDLED_PARSER 1 --feature-group master --ifname-type native --feature-disable bcmcmd --feature-disable warm-reboot --save config-db module --tclist-csv TestBGPConfed.test_confed_route_distribution_with_rmap,TestBGPConfed.test_ipv6_confed_route_distribution,TestBGPConfed.test_ipv6_confed_with_rr,TestBGPIPvxRouteAdvertisementFilter.test_bgp_ebgp4_nbr_authentication,TestBGPIPvxRouteAdvertisementFilter.test_bgp_ebgp4_nbr_update_source,TestBGPIPvxRouteAdvertisementFilter.test_bgp_route_map_with_community,TestBGPIPvxRouteAdvertisementFilter.test_default_originate_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_distribute_list_in_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_distribute_list_in_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_filter_list_in_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_filter_list_in_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_filter_list_out_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_prefix_list_out_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_prefix_list_out_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_route_aggregate_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_route_map_in_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_route_map_in_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_static_blackhole_rt_redistribute_with_routemap_ipv6,TestBGPL3Lag.test_ft_bgp_l3lag_peer_traffic_check,TestBGPRif.test_bgp_route_aggregation_4byteASN,TestBGPRif.test_ft_bgp_clear,TestBGPRif.test_ft_bgp_graceful_restart_and_aware_routers,TestBGPRif.test_ft_bgp_peer_traffic_check,TestBGPRif.test_ft_bgp_rmap,TestBGPRif.test_ft_bgp_v4_dyn_nbr,TestBGPRif.test_ft_bgp_v6_dyn_nbr,TestBGPRif.test_ft_bgp_v6_link_local_bgp,TestBGPRrTraffic.test_ft_bgp6_rr_traffic_check,TestBGPVeLag.test_ft_bgp_clear,TestBGPVeLag.test_ft_bgp_peer_traffic_check,test_VrfFun001_06,test_VrfFun_05_50,test_VrfFun_10_12_14,test_VrfFun_20_24_25_32_33_44_45,test_VrfFun_26_27,test_cli_validation_bgp_router_config,test_cli_validation_ip_address,test_ft_arp_dynamic_renew_traffic_test,test_ft_bgp_ebgp_community_map,test_ft_bgp_ibgp_RR_Loop,test_ft_ip6_static_route_traffic_forward_blackhole,test_ft_ip_static_ip_on_mgmt_intrf,test_ft_ip_static_route_traffic_forward,test_ft_ip_v4_v6_L2_L3_translation,test_ft_ipv6_neighbor_entry,test_ft_l3_performance_enhancements_v4_route_intstall_withdraw,test_ft_nat_docker_restart,test_ft_ping_v4_v6_after_ip_change_pc,test_ft_ping_v4_v6_vlan,test_ft_qos_config_mgmt_verifying_config_with_save_reboot,test_ft_sflow_max_sflow_collector_config,test_ft_sflow_sampling_v6_sFlow_collector,test_ft_system_config_mgmt_verifying_config_with_save_reboot_sflow,test_ft_verify_interfaces_order,test_l2_to_l3_port,test_l3_v4_route_po_1,test_vrf_bgp,test_vrf_reload,test_vrf_route_leak,test_vrf_scale,TestBGPRif.test_ft_bgp_ipv4_no_route_aggregation_for_exact_prefix_match,TestBGPRif.test_ft_bgp_ipv4_route_aggregation_atomic_aggregate_without_as_set,TestBGPRif.test_ft_bgp_ipv6_route_aggregation_with_as_set,TestBGPRif.test_ft_bgp_v4_max_dyn_nbr,TestBGPIPvxRouteAdvertisementFilter.test_redistribute_connected_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_redistribute_static_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_redistribute_connected_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_redistribute_static_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_default_originate_ipv6,test_spytest_infra_first,test_spytest_infra_second,test_spytest_infra_last --noop

2024-01-06 00:50:26,447 T0000: NOTICE ARGS: --logs-level debug --results-prefix=results --get-tech-support none --fetch-core-files none --syslog-check none --save config-db module --topology-check module --logs-path logs/2024-01-06-00-50-16 --continue-on-collection-errors --max-time session 0 --max-time module 0 --max-time function 0 --noop --tryssh=0 --testbed-file testbed.yaml --env SPYTEST_RPS_DEBUG 0 --tclist-bucket 1,2,4 --test-suite community-vs-l3 --email rama.kristipati@broadcom.com --env SPYTEST_SCAPY_DBG_LVL 2 --noop --env SPYTEST_EMAIL_FROM SPyTest-VSNet@broadcom.com --noop --logs-path logs/docker-master-448374-l3 --env SPYTEST_EMAIL_BODY_PREFIX http://10.193.81.56:8080/sonic_mgmt_master/work/logs/docker-master-448374-l3/dashboard.html --email-subject-nargs VSNet-sonic_mgmt_master-DOCKER-L3-{{bldver}} : {{passrate}}: {{pass_cnt}}/{{executed}} docker-master-448374-l3 --noop --feature-group master
2024-01-06 00:50:27,056 T0000: DEBUG 'errors' not set in properties for V1 assuming 'default'
2024-01-06 00:50:27,056 T0000: DEBUG 'errors' not set in properties for V2 assuming 'default'
2024-01-06 00:50:27,056 T0000: DEBUG 'errors' not set in properties for V3 assuming 'default'
2024-01-06 00:50:27,056 T0000: DEBUG 'errors' not set in properties for V4 assuming 'default'
2024-01-06 00:50:27,057 T0000: INFO  TGEN-IP 127.0.0.1
2024-01-06 00:50:27,057 T0000: WARN  Registering Topology
2024-01-06 00:50:27,081 T0000: INFO  Connecting all devices
2024-01-06 00:50:27,082 T0000: INFO  Loading scapy:1.0 127.0.0.1 Ports: ['1/1', '1/2', '1/3', '1/4', '1/5', '1/6', '1/7', '1/8', '1/9', '1/10', '1/11', '1/12', '1/13', '1/14', '1/15', '1/16'] skip: False
2024-01-06 00:50:28,054 T0012: INFO  [D1-V1] Connecting to device (V1): sonic_ssh: 172.18.0.2:22 ..
2024-01-06 00:50:28,054 T0012: INFO  [D1-V1] TRY Authentication: 172.18.0.2:22 admin YourPaSsWoRd
2024-01-06 00:50:28,060 T0013: INFO  [D2-V2] Connecting to device (V2): sonic_ssh: 172.18.0.3:22 ..
2024-01-06 00:50:28,062 T0013: INFO  [D2-V2] TRY Authentication: 172.18.0.3:22 admin YourPaSsWoRd
2024-01-06 00:50:28,067 T0014: INFO  [D3-V3] Connecting to device (V3): sonic_ssh: 172.18.0.4:22 ..
2024-01-06 00:50:28,068 T0014: INFO  [D3-V3] TRY Authentication: 172.18.0.4:22 admin YourPaSsWoRd
2024-01-06 00:50:28,075 T0015: INFO  [D4-V4] Connecting to device (V4): sonic_ssh: 172.18.0.5:22 ..
2024-01-06 00:50:28,076 T0015: INFO  [D4-V4] TRY Authentication: 172.18.0.5:22 admin YourPaSsWoRd
2024-01-06 00:50:28,113 T0000: INFO  TG Scapy Init
2024-01-06 00:50:28,114 T0000: INFO  TG Base Init skip: False
2024-01-06 00:50:28,124 T0000: INFO  TG Scapy Connect 127.0.0.1:8009
2024-01-06 00:50:28,218 T0000: INFO  Server Logs Path /data/work/scapy-tgen/logs/current/inst-2024_01_06_00_50_28_152327/gw1/default.log
2024-01-06 00:50:28,225 T0000: DEBUG REQ: tg_connect(port_list=['1/1', '1/2', '1/3', '1/4', '1/5', '1/6', '1/7', '1/8', '1/9', '1/10', '1/11', '1/12', '1/13', '1/14', '1/15', '1/16'])
2024-01-06 00:50:33,268 T0012: DEBUG [D1-V1] Connected ...
2024-01-06 00:50:33,271 T0013: DEBUG [D2-V2] Connected ...
2024-01-06 00:50:33,311 T0014: DEBUG [D3-V3] Connected ...
2024-01-06 00:50:33,315 T0015: DEBUG [D4-V4] Connected ...
2024-01-06 00:50:34,097 T0012: INFO  [D1-V1] Prompt at the connection start: 'admin@V1:~$' 
2024-01-06 00:50:34,099 T0012: AUDIT [D1-V1] ['export TMOUT=0', 'stty cols 5000', 'uptime']
2024-01-06 00:50:34,102 T0013: INFO  [D2-V2] Prompt at the connection start: 'admin@V2:~$' 
2024-01-06 00:50:34,103 T0013: AUDIT [D2-V2] ['export TMOUT=0', 'stty cols 5000', 'uptime']
2024-01-06 00:50:34,120 T0014: INFO  [D3-V3] Prompt at the connection start: 'admin@V3:~$' 
2024-01-06 00:50:34,121 T0014: AUDIT [D3-V3] ['export TMOUT=0', 'stty cols 5000', 'uptime']
2024-01-06 00:50:34,126 T0015: INFO  [D4-V4] Prompt at the connection start: 'admin@V4:~$' 
2024-01-06 00:50:34,126 T0015: AUDIT [D4-V4] ['export TMOUT=0', 'stty cols 5000', 'uptime']
2024-01-06 00:50:34,514 T0012: INFO  [D1-V1] FCMD: export TMOUT=0;stty cols 5000;uptime
2024-01-06 00:50:34,519 T0013: INFO  [D2-V2] FCMD: export TMOUT=0;stty cols 5000;uptime
2024-01-06 00:50:34,531 T0014: INFO  [D3-V3] FCMD: export TMOUT=0;stty cols 5000;uptime
2024-01-06 00:50:34,537 T0015: INFO  [D4-V4] FCMD: export TMOUT=0;stty cols 5000;uptime
2024-01-06 00:50:34,775 T0012: INFO  [D1-V1]  00:50:34 up 29 days,  1:55,  1 user,  load average: 58.39, 24.30, 13.47
2024-01-06 00:50:34,775 T0012: INFO  [D1-V1] admin@V1:~$ 
2024-01-06 00:50:34,785 T0012: AUDIT [D1-V1] cat /proc/uptime
2024-01-06 00:50:34,788 T0013: INFO  [D2-V2]  00:50:34 up 29 days,  1:55,  1 user,  load average: 58.39, 24.30, 13.47
2024-01-06 00:50:34,788 T0013: INFO  [D2-V2] admin@V2:~$ 
2024-01-06 00:50:34,790 T0013: AUDIT [D2-V2] cat /proc/uptime
2024-01-06 00:50:34,796 T0014: INFO  [D3-V3]  00:50:34 up 29 days,  1:55,  1 user,  load average: 58.39, 24.30, 13.47
2024-01-06 00:50:34,797 T0014: INFO  [D3-V3] admin@V3:~$ 
2024-01-06 00:50:34,799 T0014: AUDIT [D3-V3] cat /proc/uptime
2024-01-06 00:50:34,804 T0015: INFO  [D4-V4]  00:50:34 up 29 days,  1:55,  1 user,  load average: 58.39, 24.30, 13.47
2024-01-06 00:50:34,804 T0015: INFO  [D4-V4] admin@V4:~$ 
2024-01-06 00:50:34,805 T0015: AUDIT [D4-V4] cat /proc/uptime
2024-01-06 00:50:35,191 T0012: INFO  [D1-V1] FCMD: cat /proc/uptime
2024-01-06 00:50:35,199 T0013: INFO  [D2-V2] FCMD: cat /proc/uptime
2024-01-06 00:50:35,206 T0014: INFO  [D3-V3] FCMD: cat /proc/uptime
2024-01-06 00:50:35,210 T0015: INFO  [D4-V4] FCMD: cat /proc/uptime
2024-01-06 00:50:35,447 T0012: INFO  [D1-V1] 2512557.30 198047771.11
2024-01-06 00:50:35,447 T0012: INFO  [D1-V1] admin@V1:~$ 
2024-01-06 00:50:35,449 T0012: INFO  [D1-V1] UPTIME: 2512557.30
2024-01-06 00:50:35,450 T0012: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:35,456 T0013: INFO  [D2-V2] 2512557.31 198047771.51
2024-01-06 00:50:35,456 T0013: INFO  [D2-V2] admin@V2:~$ 
2024-01-06 00:50:35,458 T0013: INFO  [D2-V2] UPTIME: 2512557.31
2024-01-06 00:50:35,458 T0013: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:35,464 T0014: INFO  [D3-V3] 2512557.32 198047772.35
2024-01-06 00:50:35,464 T0014: INFO  [D3-V3] admin@V3:~$ 
2024-01-06 00:50:35,466 T0014: INFO  [D3-V3] UPTIME: 2512557.32
2024-01-06 00:50:35,466 T0014: AUDIT [D3-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:35,518 T0015: INFO  [D4-V4] 2512557.32 198047772.66
2024-01-06 00:50:35,519 T0015: INFO  [D4-V4] admin@V4:~$ 
2024-01-06 00:50:35,522 T0015: INFO  [D4-V4] UPTIME: 2512557.32
2024-01-06 00:50:35,522 T0015: AUDIT [D4-V4] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:35,859 T0012: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:35,867 T0013: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:35,873 T0014: INFO  [D3-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:35,929 T0015: INFO  [D4-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:36,469 T0012: INFO  [D1-V1] Error response from daemon: No such container: bgp
2024-01-06 00:50:36,470 T0012: INFO  [D1-V1] admin@V1:~$ 
2024-01-06 00:50:36,472 T0012: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:36,474 T0012: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:50:36,475 T0012: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:50:36,477 T0013: INFO  [D2-V2] Error response from daemon: No such container: bgp
2024-01-06 00:50:36,477 T0013: INFO  [D2-V2] admin@V2:~$ 
2024-01-06 00:50:36,480 T0013: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:36,480 T0013: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:50:36,481 T0013: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:50:36,533 T0014: INFO  [D3-V3] Error response from daemon: No such container: bgp
2024-01-06 00:50:36,533 T0014: INFO  [D3-V3] admin@V3:~$ 
2024-01-06 00:50:36,536 T0014: WARN  [D3-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:36,536 T0014: WARN  [D3-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:50:36,537 T0014: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:50:36,541 T0015: INFO  [D4-V4] Error response from daemon: No such container: bgp
2024-01-06 00:50:36,541 T0015: INFO  [D4-V4] admin@V4:~$ 
2024-01-06 00:50:36,544 T0015: WARN  [D4-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:36,546 T0015: WARN  [D4-V4] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:50:36,546 T0015: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:50:41,481 T0012: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:41,486 T0013: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:41,542 T0014: AUDIT [D3-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:41,552 T0015: AUDIT [D4-V4] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:41,888 T0012: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:41,893 T0013: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:41,949 T0014: INFO  [D3-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:41,960 T0015: INFO  [D4-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:42,498 T0012: INFO  [D1-V1] Error response from daemon: No such container: bgp
2024-01-06 00:50:42,498 T0012: INFO  [D1-V1] admin@V1:~$ 
2024-01-06 00:50:42,501 T0012: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:42,503 T0013: INFO  [D2-V2] Error response from daemon: No such container: bgp
2024-01-06 00:50:42,504 T0013: INFO  [D2-V2] admin@V2:~$ 
2024-01-06 00:50:42,506 T0012: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:50:42,506 T0012: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:50:42,508 T0013: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:42,510 T0013: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:50:42,511 T0013: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:50:42,560 T0014: INFO  [D3-V3] Error response from daemon: No such container: bgp
2024-01-06 00:50:42,560 T0014: INFO  [D3-V3] admin@V3:~$ 
2024-01-06 00:50:42,563 T0014: WARN  [D3-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:42,564 T0014: WARN  [D3-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:50:42,565 T0014: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:50:42,573 T0015: INFO  [D4-V4] Error response from daemon: No such container: bgp
2024-01-06 00:50:42,573 T0015: INFO  [D4-V4] admin@V4:~$ 
2024-01-06 00:50:42,576 T0015: WARN  [D4-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:42,578 T0015: WARN  [D4-V4] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:50:42,578 T0015: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:50:47,512 T0012: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:47,516 T0013: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:47,570 T0014: AUDIT [D3-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:47,584 T0015: AUDIT [D4-V4] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:47,919 T0012: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:47,926 T0013: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:47,977 T0014: INFO  [D3-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:47,992 T0015: INFO  [D4-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:48,520 T0000: DEBUG RESP: tg_connect {"port_handle": {"1/1": "port-1", "1/2": "port-2", "1/3": "port-3", "1/4": "port-4", "1/5": "port-5", "1/6": "port-6", "1/7": "port-7", "1/8": "port-8", "1/9": "port-9", "1/10": "port-10", "1/11": "port-11", "1/12": "port-12", "1/13": "port-13", "1/14": "port-14", "1/15": "port-15", "1/16": "port-16"}, "status": 1}
2024-01-06 00:50:48,543 T0000: INFO  TG Connection: Success
2024-01-06 00:50:48,543 T0000: INFO  TG Connect...done
2024-01-06 00:50:48,546 T0012: INFO  [D1-V1] Error response from daemon: No such container: bgp
2024-01-06 00:50:48,546 T0012: INFO  [D1-V1] admin@V1:~$ 
2024-01-06 00:50:48,549 T0013: INFO  [D2-V2] Error response from daemon: No such container: bgp
2024-01-06 00:50:48,549 T0013: INFO  [D2-V2] admin@V2:~$ 
2024-01-06 00:50:48,552 T0012: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:48,554 T0013: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:48,556 T0012: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:50:48,556 T0012: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:50:48,557 T0013: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:50:48,558 T0013: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:50:48,587 T0014: INFO  [D3-V3] Error response from daemon: No such container: bgp
2024-01-06 00:50:48,588 T0014: INFO  [D3-V3] admin@V3:~$ 
2024-01-06 00:50:48,590 T0014: WARN  [D3-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:48,592 T0014: WARN  [D3-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:50:48,592 T0014: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:50:48,603 T0015: INFO  [D4-V4] Error response from daemon: No such container: bgp
2024-01-06 00:50:48,603 T0015: INFO  [D4-V4] admin@V4:~$ 
2024-01-06 00:50:48,606 T0015: WARN  [D4-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:48,608 T0015: WARN  [D4-V4] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:50:48,608 T0015: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:50:53,560 T0012: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:53,560 T0013: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:53,598 T0014: AUDIT [D3-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:53,614 T0015: AUDIT [D4-V4] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:53,973 T0013: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:53,979 T0012: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:54,005 T0014: INFO  [D3-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:54,021 T0015: INFO  [D4-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:54,590 T0013: INFO  [D2-V2] Error response from daemon: No such container: bgp
2024-01-06 00:50:54,590 T0013: INFO  [D2-V2] admin@V2:~$ 
2024-01-06 00:50:54,593 T0012: INFO  [D1-V1] Error response from daemon: No such container: bgp
2024-01-06 00:50:54,593 T0012: INFO  [D1-V1] admin@V1:~$ 
2024-01-06 00:50:54,597 T0013: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:54,599 T0012: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:54,601 T0013: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:50:54,601 T0013: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:50:54,603 T0012: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:50:54,603 T0012: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:50:54,614 T0014: INFO  [D3-V3] Error response from daemon: No such container: bgp
2024-01-06 00:50:54,615 T0014: INFO  [D3-V3] admin@V3:~$ 
2024-01-06 00:50:54,617 T0014: WARN  [D3-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:54,619 T0014: WARN  [D3-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:50:54,619 T0014: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:50:54,632 T0015: INFO  [D4-V4] Error response from daemon: No such container: bgp
2024-01-06 00:50:54,632 T0015: INFO  [D4-V4] admin@V4:~$ 
2024-01-06 00:50:54,635 T0015: WARN  [D4-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:54,637 T0015: WARN  [D4-V4] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:50:54,637 T0015: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:50:59,607 T0013: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:59,608 T0012: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:59,624 T0014: AUDIT [D3-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:50:59,640 T0015: AUDIT [D4-V4] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:00,018 T0013: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:00,023 T0012: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:00,030 T0014: INFO  [D3-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:00,047 T0015: INFO  [D4-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:00,630 T0013: INFO  [D2-V2] Error response from daemon: No such container: bgp
2024-01-06 00:51:00,630 T0013: INFO  [D2-V2] admin@V2:~$ 
2024-01-06 00:51:00,633 T0012: INFO  [D1-V1] Error response from daemon: No such container: bgp
2024-01-06 00:51:00,634 T0012: INFO  [D1-V1] admin@V1:~$ 
2024-01-06 00:51:00,636 T0013: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:00,638 T0012: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:00,640 T0013: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:51:00,640 T0013: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:51:00,642 T0014: INFO  [D3-V3] Error response from daemon: No such container: bgp
2024-01-06 00:51:00,642 T0014: INFO  [D3-V3] admin@V3:~$ 
2024-01-06 00:51:00,644 T0012: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:51:00,644 T0012: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:51:00,646 T0014: WARN  [D3-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:00,648 T0014: WARN  [D3-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:51:00,648 T0014: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:51:00,659 T0015: INFO  [D4-V4] Error response from daemon: No such container: bgp
2024-01-06 00:51:00,660 T0015: INFO  [D4-V4] admin@V4:~$ 
2024-01-06 00:51:00,662 T0015: WARN  [D4-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:00,664 T0015: WARN  [D4-V4] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:51:00,664 T0015: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:51:05,644 T0013: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:05,648 T0012: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:05,653 T0014: AUDIT [D3-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:05,668 T0015: AUDIT [D4-V4] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:06,051 T0013: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:06,059 T0012: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:06,063 T0014: INFO  [D3-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:06,074 T0015: INFO  [D4-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:06,683 T0015: INFO  [D4-V4] Error response from daemon: No such container: bgp
2024-01-06 00:51:06,684 T0015: INFO  [D4-V4] admin@V4:~$ 
2024-01-06 00:51:06,686 T0015: WARN  [D4-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:06,688 T0015: WARN  [D4-V4] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:51:06,688 T0015: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:51:06,716 T0013: INFO  [D2-V2] Error response from daemon: No such container: bgp
2024-01-06 00:51:06,716 T0013: INFO  [D2-V2] admin@V2:~$ 
2024-01-06 00:51:06,719 T0013: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:06,722 T0012: INFO  [D1-V1] Error response from daemon: No such container: bgp
2024-01-06 00:51:06,722 T0012: INFO  [D1-V1] admin@V1:~$ 
2024-01-06 00:51:06,724 T0013: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:51:06,724 T0013: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:51:06,726 T0014: INFO  [D3-V3] Error response from daemon: No such container: bgp
2024-01-06 00:51:06,727 T0014: INFO  [D3-V3] admin@V3:~$ 
2024-01-06 00:51:06,729 T0012: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:06,731 T0014: WARN  [D3-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:06,733 T0012: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:51:06,733 T0012: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:51:06,734 T0014: WARN  [D3-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:51:06,734 T0014: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:51:11,694 T0015: AUDIT [D4-V4] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:11,725 T0013: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:11,738 T0012: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:11,740 T0014: AUDIT [D3-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:12,101 T0015: INFO  [D4-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:12,133 T0013: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:12,152 T0014: INFO  [D3-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:12,158 T0012: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:12,712 T0015: INFO  [D4-V4] Error response from daemon: No such container: bgp
2024-01-06 00:51:12,712 T0015: INFO  [D4-V4] admin@V4:~$ 
2024-01-06 00:51:12,715 T0015: WARN  [D4-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:12,717 T0015: WARN  [D4-V4] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:51:12,717 T0015: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:51:12,793 T0013: INFO  [D2-V2] Error response from daemon: No such container: bgp
2024-01-06 00:51:12,793 T0013: INFO  [D2-V2] admin@V2:~$ 
2024-01-06 00:51:12,796 T0013: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:12,797 T0013: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:51:12,797 T0013: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:51:12,816 T0014: INFO  [D3-V3] Error response from daemon: No such container: bgp
2024-01-06 00:51:12,817 T0014: INFO  [D3-V3] admin@V3:~$ 
2024-01-06 00:51:12,819 T0014: WARN  [D3-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:12,821 T0012: INFO  [D1-V1] Error response from daemon: No such container: bgp
2024-01-06 00:51:12,821 T0012: INFO  [D1-V1] admin@V1:~$ 
2024-01-06 00:51:12,823 T0014: WARN  [D3-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:51:12,823 T0014: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:51:12,825 T0012: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:12,826 T0012: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:51:12,826 T0012: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:51:17,723 T0015: AUDIT [D4-V4] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:17,802 T0013: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:17,829 T0014: AUDIT [D3-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:17,832 T0012: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:18,130 T0015: INFO  [D4-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:18,211 T0013: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:18,238 T0014: INFO  [D3-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:18,244 T0012: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:18,741 T0015: INFO  [D4-V4] Error response from daemon: No such container: bgp
2024-01-06 00:51:18,742 T0015: INFO  [D4-V4] admin@V4:~$ 
2024-01-06 00:51:18,743 T0015: WARN  [D4-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:18,745 T0015: WARN  [D4-V4] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:51:18,745 T0015: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:51:18,822 T0013: INFO  [D2-V2] Error response from daemon: No such container: bgp
2024-01-06 00:51:18,822 T0013: INFO  [D2-V2] admin@V2:~$ 
2024-01-06 00:51:18,824 T0013: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:18,826 T0013: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:51:18,826 T0013: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:51:18,854 T0012: INFO  [D1-V1] Error response from daemon: No such container: bgp
2024-01-06 00:51:18,854 T0012: INFO  [D1-V1] admin@V1:~$ 
2024-01-06 00:51:18,856 T0012: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:18,858 T0012: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:51:18,858 T0012: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:51:18,902 T0014: INFO  [D3-V3] Error response from daemon: No such container: bgp
2024-01-06 00:51:18,902 T0014: INFO  [D3-V3] admin@V3:~$ 
2024-01-06 00:51:18,904 T0014: WARN  [D3-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:18,906 T0014: WARN  [D3-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:51:18,906 T0014: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:51:23,748 T0015: AUDIT [D4-V4] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:23,828 T0013: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:23,864 T0012: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:23,909 T0014: AUDIT [D3-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:24,156 T0015: INFO  [D4-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:24,234 T0013: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:24,272 T0012: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:24,316 T0014: INFO  [D3-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:24,766 T0015: INFO  [D4-V4] Error response from daemon: No such container: bgp
2024-01-06 00:51:24,766 T0015: INFO  [D4-V4] admin@V4:~$ 
2024-01-06 00:51:24,769 T0015: WARN  [D4-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:24,771 T0015: WARN  [D4-V4] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:51:24,771 T0015: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:51:24,845 T0013: INFO  [D2-V2] Error response from daemon: No such container: bgp
2024-01-06 00:51:24,845 T0013: INFO  [D2-V2] admin@V2:~$ 
2024-01-06 00:51:24,847 T0013: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:24,848 T0013: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:51:24,849 T0013: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:51:24,881 T0012: INFO  [D1-V1] Error response from daemon: No such container: bgp
2024-01-06 00:51:24,881 T0012: INFO  [D1-V1] admin@V1:~$ 
2024-01-06 00:51:24,884 T0012: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:24,886 T0012: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:51:24,886 T0012: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:51:24,928 T0014: INFO  [D3-V3] Error response from daemon: No such container: bgp
2024-01-06 00:51:24,929 T0014: INFO  [D3-V3] admin@V3:~$ 
2024-01-06 00:51:24,932 T0014: WARN  [D3-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:24,934 T0014: WARN  [D3-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:51:24,934 T0014: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:51:29,776 T0015: AUDIT [D4-V4] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:29,852 T0013: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:29,888 T0012: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:29,936 T0014: AUDIT [D3-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:30,184 T0015: INFO  [D4-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:30,259 T0013: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:30,294 T0012: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:30,343 T0014: INFO  [D3-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:30,795 T0015: INFO  [D4-V4] Error response from daemon: No such container: bgp
2024-01-06 00:51:30,795 T0015: INFO  [D4-V4] admin@V4:~$ 
2024-01-06 00:51:30,798 T0015: WARN  [D4-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:30,802 T0015: WARN  [D4-V4] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:51:30,803 T0015: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:51:30,871 T0013: INFO  [D2-V2] Error response from daemon: No such container: bgp
2024-01-06 00:51:30,872 T0013: INFO  [D2-V2] admin@V2:~$ 
2024-01-06 00:51:30,874 T0013: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:30,876 T0013: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:51:30,876 T0013: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:51:30,903 T0012: INFO  [D1-V1] Error response from daemon: No such container: bgp
2024-01-06 00:51:30,903 T0012: INFO  [D1-V1] admin@V1:~$ 
2024-01-06 00:51:30,906 T0012: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:30,908 T0012: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:51:30,908 T0012: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:51:30,952 T0014: INFO  [D3-V3] Error response from daemon: No such container: bgp
2024-01-06 00:51:30,952 T0014: INFO  [D3-V3] admin@V3:~$ 
2024-01-06 00:51:30,954 T0014: WARN  [D3-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:30,956 T0014: WARN  [D3-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:51:30,956 T0014: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:51:35,808 T0015: AUDIT [D4-V4] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:35,882 T0013: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:35,914 T0012: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:35,960 T0014: AUDIT [D3-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:36,215 T0015: INFO  [D4-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:36,290 T0013: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:36,322 T0012: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:36,367 T0014: INFO  [D3-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:36,828 T0015: INFO  [D4-V4] Error response from daemon: No such container: bgp
2024-01-06 00:51:36,828 T0015: INFO  [D4-V4] admin@V4:~$ 
2024-01-06 00:51:36,832 T0015: WARN  [D4-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:36,833 T0015: WARN  [D4-V4] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:51:36,833 T0015: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:51:36,900 T0013: INFO  [D2-V2] Error response from daemon: No such container: bgp
2024-01-06 00:51:36,900 T0013: INFO  [D2-V2] admin@V2:~$ 
2024-01-06 00:51:36,902 T0013: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:36,904 T0013: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:51:36,904 T0013: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:51:36,932 T0012: INFO  [D1-V1] Error response from daemon: No such container: bgp
2024-01-06 00:51:36,932 T0012: INFO  [D1-V1] admin@V1:~$ 
2024-01-06 00:51:36,935 T0012: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:36,937 T0012: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:51:36,937 T0012: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:51:36,979 T0014: INFO  [D3-V3] Error response from daemon: No such container: bgp
2024-01-06 00:51:36,979 T0014: INFO  [D3-V3] admin@V3:~$ 
2024-01-06 00:51:36,982 T0014: WARN  [D3-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:36,984 T0014: WARN  [D3-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:51:36,984 T0014: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:51:41,839 T0015: AUDIT [D4-V4] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:41,910 T0013: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:41,942 T0012: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:41,989 T0014: AUDIT [D3-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:42,247 T0015: INFO  [D4-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:42,317 T0013: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:42,353 T0012: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:42,396 T0014: INFO  [D3-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:42,908 T0015: INFO  [D4-V4] Error response from daemon: No such container: bgp
2024-01-06 00:51:42,908 T0015: INFO  [D4-V4] admin@V4:~$ 
2024-01-06 00:51:42,911 T0015: WARN  [D4-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:42,913 T0015: WARN  [D4-V4] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:51:42,913 T0015: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:51:42,963 T0012: INFO  [D1-V1] Error response from daemon: No such container: bgp
2024-01-06 00:51:42,963 T0012: INFO  [D1-V1] admin@V1:~$ 
2024-01-06 00:51:42,966 T0012: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:42,968 T0012: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:51:42,968 T0012: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:51:42,977 T0013: INFO  [D2-V2] Error response from daemon: No such container: bgp
2024-01-06 00:51:42,977 T0013: INFO  [D2-V2] admin@V2:~$ 
2024-01-06 00:51:42,980 T0013: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:42,983 T0013: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:51:42,984 T0013: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:51:43,006 T0014: INFO  [D3-V3] Error response from daemon: No such container: bgp
2024-01-06 00:51:43,007 T0014: INFO  [D3-V3] admin@V3:~$ 
2024-01-06 00:51:43,009 T0014: WARN  [D3-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:43,011 T0014: WARN  [D3-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:51:43,011 T0014: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:51:47,916 T0015: AUDIT [D4-V4] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:47,972 T0012: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:47,989 T0013: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:48,016 T0014: AUDIT [D3-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:48,324 T0015: INFO  [D4-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:48,379 T0012: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:48,396 T0013: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:48,422 T0014: INFO  [D3-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:48,886 T0015: INFO  [D4-V4] Error response from daemon: No such container: bgp
2024-01-06 00:51:48,887 T0015: INFO  [D4-V4] admin@V4:~$ 
2024-01-06 00:51:48,889 T0015: WARN  [D4-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:48,891 T0015: WARN  [D4-V4] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:51:48,891 T0015: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:51:48,989 T0012: INFO  [D1-V1] Error response from daemon: No such container: bgp
2024-01-06 00:51:48,990 T0012: INFO  [D1-V1] admin@V1:~$ 
2024-01-06 00:51:48,992 T0012: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:48,993 T0012: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:51:48,993 T0012: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:51:49,005 T0013: INFO  [D2-V2] Error response from daemon: No such container: bgp
2024-01-06 00:51:49,006 T0013: INFO  [D2-V2] admin@V2:~$ 
2024-01-06 00:51:49,008 T0013: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:49,009 T0013: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:51:49,010 T0013: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:51:49,084 T0014: INFO  [D3-V3] Error response from daemon: No such container: bgp
2024-01-06 00:51:49,084 T0014: INFO  [D3-V3] admin@V3:~$ 
2024-01-06 00:51:49,085 T0014: WARN  [D3-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:49,086 T0014: WARN  [D3-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:51:49,086 T0014: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:51:53,897 T0015: AUDIT [D4-V4] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:53,996 T0012: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:54,015 T0013: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:54,088 T0014: AUDIT [D3-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:54,306 T0015: INFO  [D4-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:54,403 T0012: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:54,423 T0013: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:54,494 T0014: INFO  [D3-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:54,919 T0015: INFO  [D4-V4] Error response from daemon: No such container: bgp
2024-01-06 00:51:54,919 T0015: INFO  [D4-V4] admin@V4:~$ 
2024-01-06 00:51:54,921 T0015: WARN  [D4-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:54,923 T0015: WARN  [D4-V4] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:51:54,923 T0015: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:51:55,014 T0012: INFO  [D1-V1] Error response from daemon: No such container: bgp
2024-01-06 00:51:55,015 T0012: INFO  [D1-V1] admin@V1:~$ 
2024-01-06 00:51:55,020 T0012: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:55,023 T0012: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:51:55,023 T0012: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:51:55,033 T0013: INFO  [D2-V2] Error response from daemon: No such container: bgp
2024-01-06 00:51:55,033 T0013: INFO  [D2-V2] admin@V2:~$ 
2024-01-06 00:51:55,036 T0013: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:55,037 T0013: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:51:55,037 T0013: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:51:55,105 T0014: INFO  [D3-V3] Error response from daemon: No such container: bgp
2024-01-06 00:51:55,105 T0014: INFO  [D3-V3] admin@V3:~$ 
2024-01-06 00:51:55,108 T0014: WARN  [D3-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:51:55,109 T0014: WARN  [D3-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:51:55,109 T0014: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:51:59,929 T0015: AUDIT [D4-V4] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:00,028 T0012: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:00,041 T0013: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:00,112 T0014: AUDIT [D3-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:00,337 T0015: INFO  [D4-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:00,435 T0012: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:00,448 T0013: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:00,519 T0014: INFO  [D3-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:00,948 T0015: INFO  [D4-V4] Error response from daemon: No such container: bgp
2024-01-06 00:52:00,948 T0015: INFO  [D4-V4] admin@V4:~$ 
2024-01-06 00:52:00,950 T0015: WARN  [D4-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:00,952 T0015: WARN  [D4-V4] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:52:00,952 T0015: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:52:01,045 T0012: INFO  [D1-V1] Error response from daemon: No such container: bgp
2024-01-06 00:52:01,046 T0012: INFO  [D1-V1] admin@V1:~$ 
2024-01-06 00:52:01,048 T0012: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:01,049 T0012: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:52:01,049 T0012: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:52:01,058 T0013: INFO  [D2-V2] Error response from daemon: No such container: bgp
2024-01-06 00:52:01,058 T0013: INFO  [D2-V2] admin@V2:~$ 
2024-01-06 00:52:01,061 T0013: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:01,063 T0013: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:52:01,063 T0013: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:52:01,127 T0014: INFO  [D3-V3] Error response from daemon: No such container: bgp
2024-01-06 00:52:01,128 T0014: INFO  [D3-V3] admin@V3:~$ 
2024-01-06 00:52:01,130 T0014: WARN  [D3-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:01,132 T0014: WARN  [D3-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:52:01,132 T0014: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:52:05,956 T0015: AUDIT [D4-V4] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:06,055 T0012: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:06,069 T0013: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:06,134 T0014: AUDIT [D3-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:06,363 T0015: INFO  [D4-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:06,462 T0012: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:06,475 T0013: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:06,541 T0014: INFO  [D3-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:06,923 T0015: INFO  [D4-V4] Error response from daemon: No such container: bgp
2024-01-06 00:52:06,923 T0015: INFO  [D4-V4] admin@V4:~$ 
2024-01-06 00:52:06,925 T0015: WARN  [D4-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:06,927 T0015: WARN  [D4-V4] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:52:06,927 T0015: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:52:07,072 T0012: INFO  [D1-V1] Error response from daemon: No such container: bgp
2024-01-06 00:52:07,072 T0012: INFO  [D1-V1] admin@V1:~$ 
2024-01-06 00:52:07,075 T0012: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:07,077 T0012: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:52:07,077 T0012: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:52:07,088 T0013: INFO  [D2-V2] Error response from daemon: No such container: bgp
2024-01-06 00:52:07,089 T0013: INFO  [D2-V2] admin@V2:~$ 
2024-01-06 00:52:07,091 T0013: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:07,093 T0013: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:52:07,093 T0013: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:52:07,202 T0014: INFO  [D3-V3] Error response from daemon: No such container: bgp
2024-01-06 00:52:07,202 T0014: INFO  [D3-V3] admin@V3:~$ 
2024-01-06 00:52:07,205 T0014: WARN  [D3-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:07,206 T0014: WARN  [D3-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:52:07,207 T0014: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:52:11,932 T0015: AUDIT [D4-V4] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:12,080 T0012: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:12,096 T0013: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:12,212 T0014: AUDIT [D3-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:12,341 T0015: INFO  [D4-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:12,487 T0012: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:12,502 T0013: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:12,619 T0014: INFO  [D3-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:12,952 T0015: INFO  [D4-V4] Error response from daemon: No such container: bgp
2024-01-06 00:52:12,952 T0015: INFO  [D4-V4] admin@V4:~$ 
2024-01-06 00:52:12,954 T0015: WARN  [D4-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:12,956 T0015: WARN  [D4-V4] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:52:12,957 T0015: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:52:13,098 T0012: INFO  [D1-V1] Error response from daemon: No such container: bgp
2024-01-06 00:52:13,098 T0012: INFO  [D1-V1] admin@V1:~$ 
2024-01-06 00:52:13,101 T0012: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:13,102 T0012: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:52:13,103 T0012: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:52:13,112 T0013: INFO  [D2-V2] Error response from daemon: No such container: bgp
2024-01-06 00:52:13,112 T0013: INFO  [D2-V2] admin@V2:~$ 
2024-01-06 00:52:13,115 T0013: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:13,117 T0013: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:52:13,117 T0013: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:52:13,279 T0014: INFO  [D3-V3] Error response from daemon: No such container: bgp
2024-01-06 00:52:13,279 T0014: INFO  [D3-V3] admin@V3:~$ 
2024-01-06 00:52:13,281 T0014: WARN  [D3-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:13,284 T0014: WARN  [D3-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:52:13,284 T0014: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:52:17,960 T0015: AUDIT [D4-V4] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:18,104 T0012: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:18,122 T0013: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:18,288 T0014: AUDIT [D3-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:18,367 T0015: INFO  [D4-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:18,511 T0012: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:18,529 T0013: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:18,695 T0014: INFO  [D3-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:18,978 T0015: INFO  [D4-V4] Error response from daemon: No such container: bgp
2024-01-06 00:52:18,978 T0015: INFO  [D4-V4] admin@V4:~$ 
2024-01-06 00:52:18,980 T0015: WARN  [D4-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:18,981 T0015: WARN  [D4-V4] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:52:18,982 T0015: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:52:19,120 T0012: INFO  [D1-V1] Error response from daemon: No such container: bgp
2024-01-06 00:52:19,120 T0012: INFO  [D1-V1] admin@V1:~$ 
2024-01-06 00:52:19,123 T0012: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:19,125 T0012: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:52:19,125 T0012: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:52:19,139 T0013: INFO  [D2-V2] Error response from daemon: No such container: bgp
2024-01-06 00:52:19,140 T0013: INFO  [D2-V2] admin@V2:~$ 
2024-01-06 00:52:19,142 T0013: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:19,144 T0013: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:52:19,145 T0013: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:52:19,356 T0014: INFO  [D3-V3] Error response from daemon: No such container: bgp
2024-01-06 00:52:19,356 T0014: INFO  [D3-V3] admin@V3:~$ 
2024-01-06 00:52:19,358 T0014: WARN  [D3-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:19,360 T0014: WARN  [D3-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:52:19,360 T0014: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:52:23,987 T0015: AUDIT [D4-V4] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:24,131 T0012: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:24,150 T0013: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:24,366 T0014: AUDIT [D3-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:24,393 T0015: INFO  [D4-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:24,538 T0012: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:24,557 T0013: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:24,772 T0014: INFO  [D3-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:25,005 T0015: INFO  [D4-V4] Error response from daemon: No such container: bgp
2024-01-06 00:52:25,006 T0015: INFO  [D4-V4] admin@V4:~$ 
2024-01-06 00:52:25,008 T0015: WARN  [D4-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:25,011 T0015: WARN  [D4-V4] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:52:25,011 T0015: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:52:25,148 T0012: INFO  [D1-V1] Error response from daemon: No such container: bgp
2024-01-06 00:52:25,149 T0012: INFO  [D1-V1] admin@V1:~$ 
2024-01-06 00:52:25,151 T0012: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:25,153 T0012: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:52:25,153 T0012: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:52:25,168 T0013: INFO  [D2-V2] Error response from daemon: No such container: bgp
2024-01-06 00:52:25,168 T0013: INFO  [D2-V2] admin@V2:~$ 
2024-01-06 00:52:25,173 T0013: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:25,176 T0013: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:52:25,177 T0013: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:52:25,383 T0014: INFO  [D3-V3] Error response from daemon: No such container: bgp
2024-01-06 00:52:25,383 T0014: INFO  [D3-V3] admin@V3:~$ 
2024-01-06 00:52:25,385 T0014: WARN  [D3-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:25,387 T0014: WARN  [D3-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:52:25,387 T0014: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:52:30,016 T0015: AUDIT [D4-V4] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:30,159 T0012: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:30,180 T0013: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:30,392 T0014: AUDIT [D3-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:30,425 T0015: INFO  [D4-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:30,566 T0012: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:30,586 T0013: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:30,799 T0014: INFO  [D3-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:31,037 T0015: INFO  [D4-V4] Error response from daemon: No such container: bgp
2024-01-06 00:52:31,038 T0015: INFO  [D4-V4] admin@V4:~$ 
2024-01-06 00:52:31,041 T0015: WARN  [D4-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:31,043 T0015: WARN  [D4-V4] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:52:31,043 T0015: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:52:31,176 T0012: INFO  [D1-V1] Error response from daemon: No such container: bgp
2024-01-06 00:52:31,177 T0012: INFO  [D1-V1] admin@V1:~$ 
2024-01-06 00:52:31,179 T0012: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:31,180 T0012: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:52:31,181 T0012: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:52:31,196 T0013: INFO  [D2-V2] Error response from daemon: No such container: bgp
2024-01-06 00:52:31,196 T0013: INFO  [D2-V2] admin@V2:~$ 
2024-01-06 00:52:31,199 T0013: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:31,201 T0013: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:52:31,201 T0013: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:52:31,409 T0014: INFO  [D3-V3] Error response from daemon: No such container: bgp
2024-01-06 00:52:31,409 T0014: INFO  [D3-V3] admin@V3:~$ 
2024-01-06 00:52:31,412 T0014: WARN  [D3-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-06 00:52:31,414 T0014: WARN  [D3-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-06 00:52:31,414 T0014: INFO  Sleep for 5 sec(s)... @371
2024-01-06 00:52:36,049 T0015: ERROR [D4-V4] Failed to read hostname from vtysh - assuming sonic
2024-01-06 00:52:36,052 T0015: INFO  [D4-V4] Base Prompt: sonic
2024-01-06 00:52:36,053 T0015: DEBUG [D4-V4] Wait for system ready Ref: 866
2024-01-06 00:52:36,188 T0012: ERROR [D1-V1] Failed to read hostname from vtysh - assuming sonic
2024-01-06 00:52:36,189 T0012: INFO  [D1-V1] Base Prompt: sonic
2024-01-06 00:52:36,191 T0012: DEBUG [D1-V1] Wait for system ready Ref: 866
2024-01-06 00:52:36,208 T0013: ERROR [D2-V2] Failed to read hostname from vtysh - assuming sonic
2024-01-06 00:52:36,210 T0013: INFO  [D2-V2] Base Prompt: sonic
2024-01-06 00:52:36,211 T0013: DEBUG [D2-V2] Wait for system ready Ref: 866
2024-01-06 00:52:36,416 T0014: ERROR [D3-V3] Failed to read hostname from vtysh - assuming sonic
2024-01-06 00:52:36,418 T0014: INFO  [D3-V3] Base Prompt: sonic
2024-01-06 00:52:36,419 T0014: DEBUG [D3-V3] Wait for system ready Ref: 866
2024-01-06 00:52:36,460 T0015: INFO  [D4-V4] FCMD: sudo md5sum /etc/spytest/remote/spytest-helper.py
2024-01-06 00:52:36,596 T0012: INFO  [D1-V1] FCMD: sudo md5sum /etc/spytest/remote/spytest-helper.py
2024-01-06 00:52:36,617 T0013: INFO  [D2-V2] FCMD: sudo md5sum /etc/spytest/remote/spytest-helper.py
2024-01-06 00:52:36,716 T0015: INFO  [D4-V4] md5sum: /etc/spytest/remote/spytest-helper.py: No such file or directory
2024-01-06 00:52:36,716 T0015: INFO  [D4-V4] admin@V4:~$ 
2024-01-06 00:52:36,718 T0015: INFO  [D4-V4] MD5 different SRC: 4522abaafb8e29890a8377a810228525 DST: []
2024-01-06 00:52:36,719 T0015: INFO  [D4-V4] Trying to upload file '/repo/spytest/remote/spytest-helper.py'. attempt '1'
2024-01-06 00:52:36,720 T0015: INFO  [D4-V4] Transfer: SRC(SVR/VDI): /repo/spytest/remote/spytest-helper.py DST(V4): /tmp/spytest-helper.py
2024-01-06 00:52:36,721 T0015: ERROR [D4-V4] No mgmt IP
2024-01-06 00:52:36,722 T0015: INFO  [D4-V4] Doing SFTP transfer IP = None/YourPaSsWoRd/broadcom
2024-01-06 00:52:36,825 T0014: INFO  [D3-V3] FCMD: sudo md5sum /etc/spytest/remote/spytest-helper.py
2024-01-06 00:52:36,854 T0012: INFO  [D1-V1] md5sum: /etc/spytest/remote/spytest-helper.py: No such file or directory
2024-01-06 00:52:36,855 T0012: INFO  [D1-V1] admin@V1:~$ 
2024-01-06 00:52:36,858 T0012: INFO  [D1-V1] MD5 different SRC: 4522abaafb8e29890a8377a810228525 DST: []
2024-01-06 00:52:36,860 T0012: INFO  [D1-V1] Trying to upload file '/repo/spytest/remote/spytest-helper.py'. attempt '1'
2024-01-06 00:52:36,861 T0012: INFO  [D1-V1] Transfer: SRC(SVR/VDI): /repo/spytest/remote/spytest-helper.py DST(V1): /tmp/spytest-helper.py
2024-01-06 00:52:36,863 T0012: ERROR [D1-V1] No mgmt IP
2024-01-06 00:52:36,864 T0012: INFO  [D1-V1] Doing SFTP transfer IP = None/YourPaSsWoRd/broadcom
2024-01-06 00:52:36,874 T0013: INFO  [D2-V2] md5sum: /etc/spytest/remote/spytest-helper.py: No such file or directory
2024-01-06 00:52:36,874 T0013: INFO  [D2-V2] admin@V2:~$ 
2024-01-06 00:52:36,877 T0013: INFO  [D2-V2] MD5 different SRC: 4522abaafb8e29890a8377a810228525 DST: []
2024-01-06 00:52:36,879 T0013: INFO  [D2-V2] Trying to upload file '/repo/spytest/remote/spytest-helper.py'. attempt '1'
2024-01-06 00:52:36,880 T0013: INFO  [D2-V2] Transfer: SRC(SVR/VDI): /repo/spytest/remote/spytest-helper.py DST(V2): /tmp/spytest-helper.py
2024-01-06 00:52:36,882 T0013: ERROR [D2-V2] No mgmt IP
2024-01-06 00:52:36,883 T0013: INFO  [D2-V2] Doing SFTP transfer IP = None/YourPaSsWoRd/broadcom
2024-01-06 00:52:36,915 T0015: INFO  [D4-V4] FCMD: sudo md5sum /tmp/spytest-helper.py
2024-01-06 00:52:37,036 T0012: INFO  [D1-V1] FCMD: sudo md5sum /tmp/spytest-helper.py
2024-01-06 00:52:37,052 T0013: INFO  [D2-V2] FCMD: sudo md5sum /tmp/spytest-helper.py
2024-01-06 00:52:37,082 T0014: INFO  [D3-V3] md5sum: /etc/spytest/remote/spytest-helper.py: No such file or directory
2024-01-06 00:52:37,082 T0014: INFO  [D3-V3] admin@V3:~$ 
2024-01-06 00:52:37,085 T0014: INFO  [D3-V3] MD5 different SRC: 4522abaafb8e29890a8377a810228525 DST: []
2024-01-06 00:52:37,086 T0014: INFO  [D3-V3] Trying to upload file '/repo/spytest/remote/spytest-helper.py'. attempt '1'
2024-01-06 00:52:37,087 T0014: INFO  [D3-V3] Transfer: SRC(SVR/VDI): /repo/spytest/remote/spytest-helper.py DST(V3): /tmp/spytest-helper.py
2024-01-06 00:52:37,089 T0014: ERROR [D3-V3] No mgmt IP
2024-01-06 00:52:37,090 T0014: INFO  [D3-V3] Doing SFTP transfer IP = None/YourPaSsWoRd/broadcom
2024-01-06 00:52:37,173 T0015: INFO  [D4-V4] 4522abaafb8e29890a8377a810228525  /tmp/spytest-helper.py
2024-01-06 00:52:37,174 T0015: INFO  [D4-V4] admin@V4:~$ 
2024-01-06 00:52:37,177 T0015: INFO  [D4-V4] Trying to copy file to '/etc/spytest/remote/spytest-helper.py'. attempt '1'
2024-01-06 00:52:37,178 T0015: INFO  [D4-V4] SCMD: sudo mkdir -p /etc/spytest/remote && sudo cp -f /tmp/spytest-helper.py /etc/spytest/remote/spytest-helper.py
2024-01-06 00:52:37,285 T0014: INFO  [D3-V3] FCMD: sudo md5sum /tmp/spytest-helper.py
2024-01-06 00:52:37,293 T0012: INFO  [D1-V1] 4522abaafb8e29890a8377a810228525  /tmp/spytest-helper.py
2024-01-06 00:52:37,293 T0012: INFO  [D1-V1] admin@V1:~$ 
2024-01-06 00:52:37,296 T0012: INFO  [D1-V1] Trying to copy file to '/etc/spytest/remote/spytest-helper.py'. attempt '1'
2024-01-06 00:52:37,297 T0012: INFO  [D1-V1] SCMD: sudo mkdir -p /etc/spytest/remote && sudo cp -f /tmp/spytest-helper.py /etc/spytest/remote/spytest-helper.py
2024-01-06 00:52:37,309 T0013: INFO  [D2-V2] 4522abaafb8e29890a8377a810228525  /tmp/spytest-helper.py
2024-01-06 00:52:37,310 T0013: INFO  [D2-V2] admin@V2:~$ 
2024-01-06 00:52:37,313 T0013: INFO  [D2-V2] Trying to copy file to '/etc/spytest/remote/spytest-helper.py'. attempt '1'
2024-01-06 00:52:37,314 T0013: INFO  [D2-V2] SCMD: sudo mkdir -p /etc/spytest/remote && sudo cp -f /tmp/spytest-helper.py /etc/spytest/remote/spytest-helper.py
2024-01-06 00:52:37,542 T0014: INFO  [D3-V3] 4522abaafb8e29890a8377a810228525  /tmp/spytest-helper.py
2024-01-06 00:52:37,542 T0014: INFO  [D3-V3] admin@V3:~$ 
2024-01-06 00:52:37,544 T0014: INFO  [D3-V3] Trying to copy file to '/etc/spytest/remote/spytest-helper.py'. attempt '1'
2024-01-06 00:52:37,546 T0014: INFO  [D3-V3] SCMD: sudo mkdir -p /etc/spytest/remote && sudo cp -f /tmp/spytest-helper.py /etc/spytest/remote/spytest-helper.py
2024-01-06 00:52:39,787 T0015: INFO  [D4-V4] admin@V4:~$ 
2024-01-06 00:52:39,789 T0015: WARN  [D4-V4] Execute 'sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300' with timeout 600 sec -- TRY 1
2024-01-06 00:52:39,791 T0015: INFO  [D4-V4] SCMD: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2024-01-06 00:52:39,904 T0012: INFO  [D1-V1] admin@V1:~$ 
2024-01-06 00:52:39,907 T0012: WARN  [D1-V1] Execute 'sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300' with timeout 600 sec -- TRY 1
2024-01-06 00:52:39,908 T0012: INFO  [D1-V1] SCMD: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2024-01-06 00:52:39,922 T0013: INFO  [D2-V2] admin@V2:~$ 
2024-01-06 00:52:39,925 T0013: WARN  [D2-V2] Execute 'sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300' with timeout 600 sec -- TRY 1
2024-01-06 00:52:39,926 T0013: INFO  [D2-V2] SCMD: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2024-01-06 00:52:40,152 T0014: INFO  [D3-V3] admin@V3:~$ 
2024-01-06 00:52:40,155 T0014: WARN  [D3-V3] Execute 'sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300' with timeout 600 sec -- TRY 1
2024-01-06 00:52:40,156 T0014: INFO  [D3-V3] SCMD: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2024-01-06 00:52:43,617 T0015: WARN  [D4-V4] Skipped error checking in session init but detected pattern: containing_python_traceback command: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2024-01-06 00:52:43,618 T0015: INFO  [D4-V4] 
2024-01-06 00:52:43,618 T0015: INFO  [D4-V4] Remote CMD: 'show platform summary'
2024-01-06 00:52:43,619 T0015: INFO  [D4-V4] Error: Failed to execute 'show platform summary' (out: '') (err: 'Traceback (most recent call last):
2024-01-06 00:52:43,621 T0015: INFO  [D4-V4]   File "/usr/local/bin/show", line 5, in <module>
2024-01-06 00:52:43,621 T0015: INFO  [D4-V4]     from show.main import cli
2024-01-06 00:52:43,621 T0015: INFO  [D4-V4]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2024-01-06 00:52:43,622 T0015: INFO  [D4-V4]     if is_gearbox_configured():
2024-01-06 00:52:43,622 T0015: INFO  [D4-V4]        ^^^^^^^^^^^^^^^^^^^^^^^
2024-01-06 00:52:43,622 T0015: INFO  [D4-V4]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2024-01-06 00:52:43,622 T0015: INFO  [D4-V4]     app_db.connect(app_db.APPL_DB)
2024-01-06 00:52:43,623 T0015: INFO  [D4-V4]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2024-01-06 00:52:43,623 T0015: INFO  [D4-V4]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2024-01-06 00:52:43,623 T0015: INFO  [D4-V4]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-06 00:52:43,623 T0015: INFO  [D4-V4] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2024-01-06 00:52:43,623 T0015: INFO  [D4-V4] 
2024-01-06 00:52:43,624 T0015: INFO  [D4-V4] Remote CMD: 'cat /usr/share/sonic/device/None/None/port_config.ini | tail -1'
2024-01-06 00:52:43,624 T0015: INFO  [D4-V4] Remote CMD: 'sudo show interfaces status '
2024-01-06 00:52:43,624 T0015: INFO  [D4-V4] Error: Failed to execute 'sudo show interfaces status ' (out: '') (err: 'Traceback (most recent call last):
2024-01-06 00:52:43,624 T0015: INFO  [D4-V4]   File "/usr/local/bin/show", line 5, in <module>
2024-01-06 00:52:43,624 T0015: INFO  [D4-V4]     from show.main import cli
2024-01-06 00:52:43,624 T0015: INFO  [D4-V4]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2024-01-06 00:52:43,624 T0015: INFO  [D4-V4]     if is_gearbox_configured():
2024-01-06 00:52:43,625 T0015: INFO  [D4-V4]        ^^^^^^^^^^^^^^^^^^^^^^^
2024-01-06 00:52:43,625 T0015: INFO  [D4-V4]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2024-01-06 00:52:43,625 T0015: INFO  [D4-V4]     app_db.connect(app_db.APPL_DB)
2024-01-06 00:52:43,625 T0015: INFO  [D4-V4]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2024-01-06 00:52:43,625 T0015: INFO  [D4-V4]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2024-01-06 00:52:43,625 T0015: INFO  [D4-V4]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-06 00:52:43,625 T0015: INFO  [D4-V4] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2024-01-06 00:52:43,625 T0015: INFO  [D4-V4] 
2024-01-06 00:52:43,626 T0015: INFO  [D4-V4] admin@V4:~$ 
2024-01-06 00:52:43,627 T0015: ERROR [D4-V4] Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2024-01-06 00:52:43,732 T0012: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_python_traceback command: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2024-01-06 00:52:43,733 T0012: INFO  [D1-V1] 
2024-01-06 00:52:43,733 T0012: INFO  [D1-V1] Remote CMD: 'show platform summary'
2024-01-06 00:52:43,733 T0012: INFO  [D1-V1] Error: Failed to execute 'show platform summary' (out: '') (err: 'Traceback (most recent call last):
2024-01-06 00:52:43,733 T0012: INFO  [D1-V1]   File "/usr/local/bin/show", line 5, in <module>
2024-01-06 00:52:43,733 T0012: INFO  [D1-V1]     from show.main import cli
2024-01-06 00:52:43,733 T0012: INFO  [D1-V1]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2024-01-06 00:52:43,733 T0012: INFO  [D1-V1]     if is_gearbox_configured():
2024-01-06 00:52:43,733 T0012: INFO  [D1-V1]        ^^^^^^^^^^^^^^^^^^^^^^^
2024-01-06 00:52:43,733 T0012: INFO  [D1-V1]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2024-01-06 00:52:43,733 T0012: INFO  [D1-V1]     app_db.connect(app_db.APPL_DB)
2024-01-06 00:52:43,733 T0012: INFO  [D1-V1]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2024-01-06 00:52:43,733 T0012: INFO  [D1-V1]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2024-01-06 00:52:43,733 T0012: INFO  [D1-V1]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-06 00:52:43,733 T0012: INFO  [D1-V1] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2024-01-06 00:52:43,733 T0012: INFO  [D1-V1] 
2024-01-06 00:52:43,734 T0012: INFO  [D1-V1] Remote CMD: 'cat /usr/share/sonic/device/None/None/port_config.ini | tail -1'
2024-01-06 00:52:43,734 T0012: INFO  [D1-V1] Remote CMD: 'sudo show interfaces status '
2024-01-06 00:52:43,734 T0012: INFO  [D1-V1] Error: Failed to execute 'sudo show interfaces status ' (out: '') (err: 'Traceback (most recent call last):
2024-01-06 00:52:43,734 T0012: INFO  [D1-V1]   File "/usr/local/bin/show", line 5, in <module>
2024-01-06 00:52:43,734 T0012: INFO  [D1-V1]     from show.main import cli
2024-01-06 00:52:43,734 T0012: INFO  [D1-V1]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2024-01-06 00:52:43,734 T0012: INFO  [D1-V1]     if is_gearbox_configured():
2024-01-06 00:52:43,734 T0012: INFO  [D1-V1]        ^^^^^^^^^^^^^^^^^^^^^^^
2024-01-06 00:52:43,734 T0012: INFO  [D1-V1]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2024-01-06 00:52:43,734 T0012: INFO  [D1-V1]     app_db.connect(app_db.APPL_DB)
2024-01-06 00:52:43,734 T0012: INFO  [D1-V1]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2024-01-06 00:52:43,734 T0012: INFO  [D1-V1]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2024-01-06 00:52:43,734 T0012: INFO  [D1-V1]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-06 00:52:43,734 T0012: INFO  [D1-V1] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2024-01-06 00:52:43,734 T0012: INFO  [D1-V1] 
2024-01-06 00:52:43,734 T0012: INFO  [D1-V1] admin@V1:~$ 
2024-01-06 00:52:43,735 T0012: ERROR [D1-V1] Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2024-01-06 00:52:43,752 T0013: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_python_traceback command: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2024-01-06 00:52:43,753 T0013: INFO  [D2-V2] 
2024-01-06 00:52:43,753 T0013: INFO  [D2-V2] Remote CMD: 'show platform summary'
2024-01-06 00:52:43,753 T0013: INFO  [D2-V2] Error: Failed to execute 'show platform summary' (out: '') (err: 'Traceback (most recent call last):
2024-01-06 00:52:43,753 T0013: INFO  [D2-V2]   File "/usr/local/bin/show", line 5, in <module>
2024-01-06 00:52:43,753 T0013: INFO  [D2-V2]     from show.main import cli
2024-01-06 00:52:43,753 T0013: INFO  [D2-V2]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2024-01-06 00:52:43,753 T0013: INFO  [D2-V2]     if is_gearbox_configured():
2024-01-06 00:52:43,754 T0013: INFO  [D2-V2]        ^^^^^^^^^^^^^^^^^^^^^^^
2024-01-06 00:52:43,754 T0013: INFO  [D2-V2]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2024-01-06 00:52:43,754 T0013: INFO  [D2-V2]     app_db.connect(app_db.APPL_DB)
2024-01-06 00:52:43,754 T0013: INFO  [D2-V2]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2024-01-06 00:52:43,754 T0013: INFO  [D2-V2]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2024-01-06 00:52:43,754 T0013: INFO  [D2-V2]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-06 00:52:43,754 T0013: INFO  [D2-V2] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2024-01-06 00:52:43,754 T0013: INFO  [D2-V2] 
2024-01-06 00:52:43,754 T0013: INFO  [D2-V2] Remote CMD: 'cat /usr/share/sonic/device/None/None/port_config.ini | tail -1'
2024-01-06 00:52:43,754 T0013: INFO  [D2-V2] Remote CMD: 'sudo show interfaces status '
2024-01-06 00:52:43,754 T0013: INFO  [D2-V2] Error: Failed to execute 'sudo show interfaces status ' (out: '') (err: 'Traceback (most recent call last):
2024-01-06 00:52:43,754 T0013: INFO  [D2-V2]   File "/usr/local/bin/show", line 5, in <module>
2024-01-06 00:52:43,755 T0013: INFO  [D2-V2]     from show.main import cli
2024-01-06 00:52:43,755 T0013: INFO  [D2-V2]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2024-01-06 00:52:43,755 T0013: INFO  [D2-V2]     if is_gearbox_configured():
2024-01-06 00:52:43,755 T0013: INFO  [D2-V2]        ^^^^^^^^^^^^^^^^^^^^^^^
2024-01-06 00:52:43,755 T0013: INFO  [D2-V2]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2024-01-06 00:52:43,755 T0013: INFO  [D2-V2]     app_db.connect(app_db.APPL_DB)
2024-01-06 00:52:43,755 T0013: INFO  [D2-V2]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2024-01-06 00:52:43,755 T0013: INFO  [D2-V2]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2024-01-06 00:52:43,755 T0013: INFO  [D2-V2]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-06 00:52:43,755 T0013: INFO  [D2-V2] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2024-01-06 00:52:43,755 T0013: INFO  [D2-V2] 
2024-01-06 00:52:43,755 T0013: INFO  [D2-V2] admin@V2:~$ 
2024-01-06 00:52:43,756 T0013: ERROR [D2-V2] Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2024-01-06 00:52:43,984 T0014: WARN  [D3-V3] Skipped error checking in session init but detected pattern: containing_python_traceback command: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2024-01-06 00:52:43,985 T0014: INFO  [D3-V3] 
2024-01-06 00:52:43,985 T0014: INFO  [D3-V3] Remote CMD: 'show platform summary'
2024-01-06 00:52:43,985 T0014: INFO  [D3-V3] Error: Failed to execute 'show platform summary' (out: '') (err: 'Traceback (most recent call last):
2024-01-06 00:52:43,985 T0014: INFO  [D3-V3]   File "/usr/local/bin/show", line 5, in <module>
2024-01-06 00:52:43,985 T0014: INFO  [D3-V3]     from show.main import cli
2024-01-06 00:52:43,985 T0014: INFO  [D3-V3]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2024-01-06 00:52:43,985 T0014: INFO  [D3-V3]     if is_gearbox_configured():
2024-01-06 00:52:43,985 T0014: INFO  [D3-V3]        ^^^^^^^^^^^^^^^^^^^^^^^
2024-01-06 00:52:43,985 T0014: INFO  [D3-V3]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2024-01-06 00:52:43,985 T0014: INFO  [D3-V3]     app_db.connect(app_db.APPL_DB)
2024-01-06 00:52:43,985 T0014: INFO  [D3-V3]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2024-01-06 00:52:43,985 T0014: INFO  [D3-V3]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2024-01-06 00:52:43,985 T0014: INFO  [D3-V3]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-06 00:52:43,986 T0014: INFO  [D3-V3] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2024-01-06 00:52:43,986 T0014: INFO  [D3-V3] 
2024-01-06 00:52:43,986 T0014: INFO  [D3-V3] Remote CMD: 'cat /usr/share/sonic/device/None/None/port_config.ini | tail -1'
2024-01-06 00:52:43,986 T0014: INFO  [D3-V3] Remote CMD: 'sudo show interfaces status '
2024-01-06 00:52:43,986 T0014: INFO  [D3-V3] Error: Failed to execute 'sudo show interfaces status ' (out: '') (err: 'Traceback (most recent call last):
2024-01-06 00:52:43,986 T0014: INFO  [D3-V3]   File "/usr/local/bin/show", line 5, in <module>
2024-01-06 00:52:43,986 T0014: INFO  [D3-V3]     from show.main import cli
2024-01-06 00:52:43,986 T0014: INFO  [D3-V3]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2024-01-06 00:52:43,986 T0014: INFO  [D3-V3]     if is_gearbox_configured():
2024-01-06 00:52:43,986 T0014: INFO  [D3-V3]        ^^^^^^^^^^^^^^^^^^^^^^^
2024-01-06 00:52:43,986 T0014: INFO  [D3-V3]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2024-01-06 00:52:43,986 T0014: INFO  [D3-V3]     app_db.connect(app_db.APPL_DB)
2024-01-06 00:52:43,986 T0014: INFO  [D3-V3]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2024-01-06 00:52:43,986 T0014: INFO  [D3-V3]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2024-01-06 00:52:43,986 T0014: INFO  [D3-V3]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-06 00:52:43,986 T0014: INFO  [D3-V3] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2024-01-06 00:52:43,987 T0014: INFO  [D3-V3] 
2024-01-06 00:52:43,987 T0014: INFO  [D3-V3] admin@V3:~$ 
2024-01-06 00:52:43,987 T0014: ERROR [D3-V3] Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2024-01-06 00:52:43,987 T0011: ERROR exception in thread: Traceback (most recent call last):
  File "/repo/utilities/parallel.py", line 159, in _thread_func
    retvals[index] = func(*args, **kwargs)
  File "/repo/spytest/net.py", line 1064, in connect_to_device
    show_ver_output = self.connect_to_device_real(access, retry, recon, recover)
  File "/repo/spytest/net.py", line 1290, in connect_to_device_real
    self.do_common_init(devname, phase=0, max_ready_wait=max_ready_wait)
  File "/repo/spytest/net.py", line 866, in do_common_init
    sys_status = self.wa.wait_system_status(devname, max_time=max_ready_wait)
  File "/repo/spytest/framework.py", line 1616, in wait_system_status
    return self._wait_for_ports(dut, max_time)
  File "/repo/spytest/framework.py", line 1605, in _wait_for_ports
    return self.net.apply_remote(dut, "wait-for-ports", [max_time])
  File "/repo/spytest/net.py", line 4523, in apply_remote
    raise ValueError(msg)
ValueError: Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  

2024-01-06 00:52:43,988 T0011: ERROR exception in thread: Traceback (most recent call last):
  File "/repo/utilities/parallel.py", line 159, in _thread_func
    retvals[index] = func(*args, **kwargs)
  File "/repo/spytest/net.py", line 1064, in connect_to_device
    show_ver_output = self.connect_to_device_real(access, retry, recon, recover)
  File "/repo/spytest/net.py", line 1290, in connect_to_device_real
    self.do_common_init(devname, phase=0, max_ready_wait=max_ready_wait)
  File "/repo/spytest/net.py", line 866, in do_common_init
    sys_status = self.wa.wait_system_status(devname, max_time=max_ready_wait)
  File "/repo/spytest/framework.py", line 1616, in wait_system_status
    return self._wait_for_ports(dut, max_time)
  File "/repo/spytest/framework.py", line 1605, in _wait_for_ports
    return self.net.apply_remote(dut, "wait-for-ports", [max_time])
  File "/repo/spytest/net.py", line 4523, in apply_remote
    raise ValueError(msg)
ValueError: Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  

2024-01-06 00:52:43,988 T0011: ERROR exception in thread: Traceback (most recent call last):
  File "/repo/utilities/parallel.py", line 159, in _thread_func
    retvals[index] = func(*args, **kwargs)
  File "/repo/spytest/net.py", line 1064, in connect_to_device
    show_ver_output = self.connect_to_device_real(access, retry, recon, recover)
  File "/repo/spytest/net.py", line 1290, in connect_to_device_real
    self.do_common_init(devname, phase=0, max_ready_wait=max_ready_wait)
  File "/repo/spytest/net.py", line 866, in do_common_init
    sys_status = self.wa.wait_system_status(devname, max_time=max_ready_wait)
  File "/repo/spytest/framework.py", line 1616, in wait_system_status
    return self._wait_for_ports(dut, max_time)
  File "/repo/spytest/framework.py", line 1605, in _wait_for_ports
    return self.net.apply_remote(dut, "wait-for-ports", [max_time])
  File "/repo/spytest/net.py", line 4523, in apply_remote
    raise ValueError(msg)
ValueError: Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  

2024-01-06 00:52:43,988 T0011: ERROR exception in thread: Traceback (most recent call last):
  File "/repo/utilities/parallel.py", line 159, in _thread_func
    retvals[index] = func(*args, **kwargs)
  File "/repo/spytest/net.py", line 1064, in connect_to_device
    show_ver_output = self.connect_to_device_real(access, retry, recon, recover)
  File "/repo/spytest/net.py", line 1290, in connect_to_device_real
    self.do_common_init(devname, phase=0, max_ready_wait=max_ready_wait)
  File "/repo/spytest/net.py", line 866, in do_common_init
    sys_status = self.wa.wait_system_status(devname, max_time=max_ready_wait)
  File "/repo/spytest/framework.py", line 1616, in wait_system_status
    return self._wait_for_ports(dut, max_time)
  File "/repo/spytest/framework.py", line 1605, in _wait_for_ports
    return self.net.apply_remote(dut, "wait-for-ports", [max_time])
  File "/repo/spytest/net.py", line 4523, in apply_remote
    raise ValueError(msg)
ValueError: Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  

2024-01-06 00:52:43,989 T0011: ERROR [D1-V1] Failed to connect to device
2024-01-06 00:52:43,990 T0011: ERROR [D2-V2] Failed to connect to device
2024-01-06 00:52:43,991 T0011: ERROR [D3-V3] Failed to connect to device
2024-01-06 00:52:43,991 T0011: ERROR [D4-V4] Failed to connect to device
2024-01-06 00:52:43,992 T0000: ERROR Failed to connect (['V1', 'V2', 'V3', 'V4'])
2024-01-06 00:52:43,992 T0000: INFO  --FINISH--RUN--4 @559
