2024-01-08 01:51:21,422 T0002: INFO  Connecting to device (V2): sonic_ssh: 172.18.0.3:22 ..
2024-01-08 01:51:21,423 T0002: INFO  TRY Authentication: 172.18.0.3:22 admin YourPaSsWoRd
2024-01-08 01:51:26,635 T0002: DEBUG Connected ...
2024-01-08 01:51:27,460 T0002: INFO  Prompt at the connection start: 'admin@V2:~$' 
2024-01-08 01:51:27,868 T0002: INFO  FCMD: export TMOUT=0;stty cols 5000;uptime
2024-01-08 01:51:28,750 T0002: INFO   01:51:28 up 31 days,  2:57,  1 user,  load average: 16.99, 28.49, 17.75
2024-01-08 01:51:28,766 T0002: INFO  admin@V2:~$ 
2024-01-08 01:51:29,148 T0000: INFO  
2024-01-08 01:51:29,148 T0000: INFO  ================== batch/test_spytest_infra_1.py::test_spytest_infra_first ==================
2024-01-08 01:51:29,155 T0000: INFO  Report():batch/test_spytest_infra_1.py::test_spytest_infra_first 0:00:00 module configuration failed.  @5445
2024-01-08 01:51:29,486 T0002: INFO  FCMD: cat /proc/uptime
2024-01-08 01:51:29,743 T0002: INFO  2689059.63 211901972.59
2024-01-08 01:51:29,744 T0002: INFO  admin@V2:~$ 
2024-01-08 01:51:29,746 T0002: INFO  UPTIME: 2689059.63
2024-01-08 01:51:30,154 T0002: INFO  FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:51:30,764 T0002: INFO  Error response from daemon: No such container: bgp
2024-01-08 01:51:30,765 T0002: INFO  admin@V2:~$ 
2024-01-08 01:51:30,768 T0002: WARN  Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:51:30,770 T0002: WARN  Failed to read hostname from vtysh retry again in 5 sec
