ordering items took 0:00:01
Tests considered 69 and ignored 320
2024-01-08 01:48:59,929 T0000: NOTICE WORKER = gw3
2024-01-08 01:48:59,929 T0000: NOTICE using testbed file /data/work/logs/docker-master-449712-l2/testbed_1_2_2.yaml
2024-01-08 01:48:59,929 T0000: NOTICE Execution Start Time: 2024-01-08 01:48:59.925840
2024-01-08 01:48:59,929 T0000: NOTICE LOGS PATH: /data/work/logs/docker-master-449712-l2/gw3
2024-01-08 01:49:00,484 T0000: NOTICE VERSION: UNKNOWN UNKNOWN UNKNOWN
2024-01-08 01:49:00,484 T0000: NOTICE HOST: sonicmgmtmaster MEM: 376gb 56.8%
2024-01-08 01:49:00,484 T0000: NOTICE ROOT_PATH: /repo
2024-01-08 01:49:00,484 T0000: NOTICE Python: 3.8.10
2024-01-08 01:49:00,484 T0000: NOTICE Topology unknown: D1T1:4,D1D2:6,D2T1:4
2024-01-08 01:49:00,484 T0000: DEBUG 
SUITE ARGS: --load-image none --max-time module 9000 --max-time function 5400 --max-time session 3600 --logs-level=debug --topology-check=function --env SPYTEST_TESTBED_IGNORE_CONSTRAINTS TG,TGCARD,TGSPEED,CHIP,MODEL --noop --env SPYTEST_RESET_CONSOLES 0 --noop --env SPYTEST_ONREBOOT_RENEW_MGMT_IP 1 --noop --env SPYTEST_RECOVERY_CR_PER_CMD_POST_OP 1 --noop --env SPYTEST_BATCH_POLL_STATUS_TIME 300 --noop --env SPYTEST_BATCH_DEAD_NODE_MAX_TIME 7200 --noop --breakout-mode none --env SPYTEST_SHUTDOWN_FREE_PORTS 1 --env SPYTEST_HOOKS_BREAKOUT_UITYPE click --env SPYTEST_ONREBOOT_RENEW_MGMT_IP 0 --env SPYTEST_VERIFY_CSV_MIN_TOPOLOGY 1 --env SPYTEST_CMD_FAIL_RESULT_SUPPORT 0 --env SPYTEST_ROUTING_CONFIG_MODE split --env SPYTEST_CLEAR_DEVICE_METADATA_BGP_ASN 1 --env SPYTEST_TEXTFSM_USE_BUNDLED_PARSER 1 --feature-group master --ifname-type native --feature-disable bcmcmd --feature-disable warm-reboot --save config-db module --tclist-csv test_ft_add_unknownvlan_interface,test_ft_lldp_ConfigManAddrEntry,test_ft_lldp_LocManAddrEntry,test_ft_lldp_LocManAddrLen,test_ft_lldp_LocManAddrlfld,test_ft_lldp_docker_restart,test_ft_lldp_lldplocportid,test_ft_lldp_lldplocsysdesc,test_ft_lldp_lldplocsysname,test_ft_lldp_non_default_config,test_ft_lldp_rem_man_addr_table,test_ft_lldp_with_remote_server,test_ft_net_snmp_agent_mib,test_ft_net_snmp_vacm_mib,test_ft_ntp_disable_enable_with_message_log,test_ft_port_fn_verify_shut_noshut,test_ft_portchannel_with_vlan_variations,test_ft_snmp_coldstart_trap,test_ft_snmp_docker_restart,test_ft_snmp_dot1q_dot1db_mib,test_ft_snmp_dot1q_tp_fdb_address,test_ft_snmp_dot1q_tp_fdb_port,test_ft_snmp_dot3_stats_table,test_ft_snmp_ent_physical_table,test_ft_snmp_entity_mib_all,test_ft_snmp_framework_mib,test_ft_snmp_host_resource_mib,test_ft_snmp_icmp_Msgs,test_ft_snmp_if_mib_all,test_ft_snmp_ifx_table,test_ft_snmp_ipAddressRowStatus_ipv6,test_ft_snmp_ipAddressStorageType_ipv6,test_ft_snmp_ip_Address_Table,test_ft_snmp_ip_IfStats_Table,test_ft_snmp_ip_NetToPhysical_Table,test_ft_snmp_ip_System_Stats_Table,test_ft_snmp_ip_forward_table,test_ft_snmp_ipv6_If_Forward_default_HopLimit,test_ft_snmp_ipv6scope_index_table,test_ft_snmp_mib_2,test_ft_snmp_mpd_mib,test_ft_snmp_notification_mib,test_ft_snmp_root_node_walk,test_ft_snmp_snmpv2_mib,test_ft_snmp_sysDescr,test_ft_snmp_sysName,test_ft_snmp_target_mib,test_ft_snmp_tcp_mib,test_ft_snmp_test_syUpTime,test_ft_snmp_ucd_diskio_mib,test_ft_snmp_ucd_la_table,test_ft_snmp_ucd_system_stats,test_ft_snmp_udp_mib,test_ft_snmp_user_based_sm_mib,test_ft_snmp_view_based_acm_mib,test_ft_ssh_add_user_verify,test_ft_ssh_service_disable,test_ft_tacacs_ssh_login_with_tacacs_operations,test_ft_verify_logs_at_the_time_of_ssh_login_success,test_ft_verify_min_links_functionality_by_flapping_all_member_ports_007,test_ft_vlan_delete_with_member,test_ft_vlan_save_config_warm_and_fast_reboot,test_ft_vlan_trunk_tagged,test_ft_watermark_telemetry_interval,test_lldp_verify_counters,test_ntp_exists_config,test_spytest_infra_first,test_spytest_infra_second,test_spytest_infra_last --noop

2024-01-08 01:49:00,484 T0000: NOTICE ARGS: --logs-level debug --results-prefix=results --get-tech-support none --fetch-core-files none --syslog-check none --save config-db module --topology-check module --logs-path logs/2024-01-08-01-48-49 --continue-on-collection-errors --max-time session 0 --max-time module 0 --max-time function 0 --noop --tryssh=0 --testbed-file testbed.yaml --env SPYTEST_RPS_DEBUG 0 --tclist-bucket 1,2,4 --test-suite community-vs-l2 --email rama.kristipati@broadcom.com --env SPYTEST_SCAPY_DBG_LVL 2 --noop --env SPYTEST_EMAIL_FROM SPyTest-VSNet@broadcom.com --noop --logs-path logs/docker-master-449712-l2 --env SPYTEST_EMAIL_BODY_PREFIX http://10.193.81.56:8080/sonic_mgmt_master/work/logs/docker-master-449712-l2/dashboard.html --email-subject-nargs VSNet-sonic_mgmt_master-DOCKER-L2-{{bldver}} : {{passrate}}: {{pass_cnt}}/{{executed}} docker-master-449712-l2 --noop --feature-group master
2024-01-08 01:49:01,198 T0000: DEBUG 'errors' not set in properties for V1 assuming 'default'
2024-01-08 01:49:01,198 T0000: DEBUG 'errors' not set in properties for V2 assuming 'default'
2024-01-08 01:49:01,199 T0000: INFO  TGEN-IP 127.0.0.1
2024-01-08 01:49:01,199 T0000: WARN  Registering Topology
2024-01-08 01:49:01,219 T0000: INFO  Connecting all devices
2024-01-08 01:49:01,220 T0000: INFO  Loading scapy:1.0 127.0.0.1 Ports: ['1/1', '1/2', '1/3', '1/4', '1/5', '1/6', '1/7', '1/8'] skip: False
2024-01-08 01:49:01,754 T0005: INFO  [D1-V1] Connecting to device (V1): sonic_ssh: 172.18.0.2:22 ..
2024-01-08 01:49:01,754 T0005: INFO  [D1-V1] TRY Authentication: 172.18.0.2:22 admin YourPaSsWoRd
2024-01-08 01:49:01,759 T0006: INFO  [D2-V2] Connecting to device (V2): sonic_ssh: 172.18.0.3:22 ..
2024-01-08 01:49:01,760 T0006: INFO  [D2-V2] TRY Authentication: 172.18.0.3:22 admin YourPaSsWoRd
2024-01-08 01:49:02,283 T0000: INFO  TG Scapy Init
2024-01-08 01:49:02,284 T0000: INFO  TG Base Init skip: False
2024-01-08 01:49:02,294 T0000: INFO  TG Scapy Connect 127.0.0.1:8009
2024-01-08 01:49:02,415 T0000: INFO  Server Logs Path /data/work/scapy-tgen/logs/current/inst-2024_01_08_01_49_02_317853/gw3/default.log
2024-01-08 01:49:02,425 T0000: DEBUG REQ: tg_connect(port_list=['1/1', '1/2', '1/3', '1/4', '1/5', '1/6', '1/7', '1/8'])
2024-01-08 01:49:06,954 T0005: DEBUG [D1-V1] Connected ...
2024-01-08 01:49:06,977 T0006: DEBUG [D2-V2] Connected ...
2024-01-08 01:49:07,770 T0005: INFO  [D1-V1] Prompt at the connection start: 'admin@V1:~$' 
2024-01-08 01:49:07,772 T0005: AUDIT [D1-V1] ['export TMOUT=0', 'stty cols 5000', 'uptime']
2024-01-08 01:49:07,786 T0006: INFO  [D2-V2] Prompt at the connection start: 'admin@V2:~$' 
2024-01-08 01:49:07,787 T0006: AUDIT [D2-V2] ['export TMOUT=0', 'stty cols 5000', 'uptime']
2024-01-08 01:49:08,180 T0005: INFO  [D1-V1] FCMD: export TMOUT=0;stty cols 5000;uptime
2024-01-08 01:49:08,195 T0006: INFO  [D2-V2] FCMD: export TMOUT=0;stty cols 5000;uptime
2024-01-08 01:49:08,437 T0005: INFO  [D1-V1]  01:49:08 up 31 days,  2:55,  1 user,  load average: 107.72, 40.64, 19.27
2024-01-08 01:49:08,438 T0005: INFO  [D1-V1] admin@V1:~$ 
2024-01-08 01:49:08,447 T0005: AUDIT [D1-V1] cat /proc/uptime
2024-01-08 01:49:08,453 T0006: INFO  [D2-V2]  01:49:08 up 31 days,  2:55,  1 user,  load average: 107.72, 40.64, 19.27
2024-01-08 01:49:08,453 T0006: INFO  [D2-V2] admin@V2:~$ 
2024-01-08 01:49:08,455 T0006: AUDIT [D2-V2] cat /proc/uptime
2024-01-08 01:49:08,852 T0005: INFO  [D1-V1] FCMD: cat /proc/uptime
2024-01-08 01:49:08,861 T0006: INFO  [D2-V2] FCMD: cat /proc/uptime
2024-01-08 01:49:09,108 T0005: INFO  [D1-V1] 2688919.00 211891294.06
2024-01-08 01:49:09,109 T0005: INFO  [D1-V1] admin@V1:~$ 
2024-01-08 01:49:09,111 T0005: INFO  [D1-V1] UPTIME: 2688919.00
2024-01-08 01:49:09,112 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:09,116 T0006: INFO  [D2-V2] 2688919.01 211891294.79
2024-01-08 01:49:09,116 T0006: INFO  [D2-V2] admin@V2:~$ 
2024-01-08 01:49:09,117 T0006: INFO  [D2-V2] UPTIME: 2688919.01
2024-01-08 01:49:09,118 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:09,517 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:09,524 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:10,176 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2024-01-08 01:49:10,177 T0005: INFO  [D1-V1] admin@V1:~$ 
2024-01-08 01:49:10,179 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:10,181 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:49:10,182 T0005: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:49:10,335 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2024-01-08 01:49:10,336 T0006: INFO  [D2-V2] admin@V2:~$ 
2024-01-08 01:49:10,338 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:10,339 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:49:10,340 T0006: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:49:13,284 T0000: DEBUG RESP: tg_connect {"port_handle": {"1/1": "port-1", "1/2": "port-2", "1/3": "port-3", "1/4": "port-4", "1/5": "port-5", "1/6": "port-6", "1/7": "port-7", "1/8": "port-8"}, "status": 1}
2024-01-08 01:49:13,299 T0000: INFO  TG Connection: Success
2024-01-08 01:49:13,299 T0000: INFO  TG Connect...done
2024-01-08 01:49:15,186 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:15,342 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:15,593 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:15,751 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:16,256 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2024-01-08 01:49:16,256 T0005: INFO  [D1-V1] admin@V1:~$ 
2024-01-08 01:49:16,260 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:16,262 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:49:16,262 T0005: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:49:16,361 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2024-01-08 01:49:16,361 T0006: INFO  [D2-V2] admin@V2:~$ 
2024-01-08 01:49:16,364 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:16,366 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:49:16,366 T0006: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:49:21,266 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:21,370 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:21,673 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:21,779 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:22,284 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2024-01-08 01:49:22,284 T0005: INFO  [D1-V1] admin@V1:~$ 
2024-01-08 01:49:22,287 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:22,288 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:49:22,288 T0005: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:49:22,440 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2024-01-08 01:49:22,440 T0006: INFO  [D2-V2] admin@V2:~$ 
2024-01-08 01:49:22,442 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:22,443 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:49:22,443 T0006: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:49:27,294 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:27,446 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:27,701 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:27,853 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:28,312 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2024-01-08 01:49:28,312 T0005: INFO  [D1-V1] admin@V1:~$ 
2024-01-08 01:49:28,314 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:28,315 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:49:28,315 T0005: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:49:28,516 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2024-01-08 01:49:28,516 T0006: INFO  [D2-V2] admin@V2:~$ 
2024-01-08 01:49:28,519 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:28,521 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:49:28,521 T0006: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:49:33,318 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:33,526 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:33,724 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:33,933 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:34,387 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2024-01-08 01:49:34,387 T0005: INFO  [D1-V1] admin@V1:~$ 
2024-01-08 01:49:34,390 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:34,392 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:49:34,392 T0005: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:49:34,542 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2024-01-08 01:49:34,542 T0006: INFO  [D2-V2] admin@V2:~$ 
2024-01-08 01:49:34,545 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:34,547 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:49:34,548 T0006: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:49:39,398 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:39,550 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:39,805 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:39,957 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:40,417 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2024-01-08 01:49:40,417 T0005: INFO  [D1-V1] admin@V1:~$ 
2024-01-08 01:49:40,421 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:40,423 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:49:40,423 T0005: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:49:40,620 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2024-01-08 01:49:40,620 T0006: INFO  [D2-V2] admin@V2:~$ 
2024-01-08 01:49:40,623 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:40,625 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:49:40,625 T0006: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:49:45,426 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:45,630 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:45,832 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:46,037 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:46,493 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2024-01-08 01:49:46,494 T0005: INFO  [D1-V1] admin@V1:~$ 
2024-01-08 01:49:46,497 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:46,498 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:49:46,498 T0005: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:49:46,700 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2024-01-08 01:49:46,701 T0006: INFO  [D2-V2] admin@V2:~$ 
2024-01-08 01:49:46,703 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:46,705 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:49:46,705 T0006: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:49:51,504 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:51,710 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:51,912 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:52,119 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:52,573 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2024-01-08 01:49:52,573 T0005: INFO  [D1-V1] admin@V1:~$ 
2024-01-08 01:49:52,575 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:52,576 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:49:52,576 T0005: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:49:52,729 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2024-01-08 01:49:52,729 T0006: INFO  [D2-V2] admin@V2:~$ 
2024-01-08 01:49:52,732 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:52,734 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:49:52,734 T0006: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:49:57,582 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:57,738 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:57,989 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:58,146 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:58,600 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2024-01-08 01:49:58,600 T0005: INFO  [D1-V1] admin@V1:~$ 
2024-01-08 01:49:58,603 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:58,605 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:49:58,605 T0005: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:49:58,806 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2024-01-08 01:49:58,806 T0006: INFO  [D2-V2] admin@V2:~$ 
2024-01-08 01:49:58,809 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:49:58,810 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:49:58,810 T0006: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:50:03,611 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:03,816 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:04,018 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:04,223 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:04,628 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2024-01-08 01:50:04,628 T0005: INFO  [D1-V1] admin@V1:~$ 
2024-01-08 01:50:04,631 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:04,633 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:50:04,634 T0005: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:50:04,833 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2024-01-08 01:50:04,833 T0006: INFO  [D2-V2] admin@V2:~$ 
2024-01-08 01:50:04,835 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:04,836 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:50:04,836 T0006: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:50:09,638 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:09,838 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:10,048 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:10,246 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:10,707 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2024-01-08 01:50:10,707 T0005: INFO  [D1-V1] admin@V1:~$ 
2024-01-08 01:50:10,708 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:10,709 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:50:10,709 T0005: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:50:10,857 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2024-01-08 01:50:10,857 T0006: INFO  [D2-V2] admin@V2:~$ 
2024-01-08 01:50:10,860 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:10,861 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:50:10,862 T0006: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:50:15,715 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:15,866 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:16,124 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:16,271 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:16,736 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2024-01-08 01:50:16,736 T0005: INFO  [D1-V1] admin@V1:~$ 
2024-01-08 01:50:16,739 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:16,741 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:50:16,741 T0005: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:50:16,934 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2024-01-08 01:50:16,934 T0006: INFO  [D2-V2] admin@V2:~$ 
2024-01-08 01:50:16,939 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:16,942 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:50:16,942 T0006: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:50:21,747 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:21,946 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:22,154 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:22,353 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:22,764 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2024-01-08 01:50:22,764 T0005: INFO  [D1-V1] admin@V1:~$ 
2024-01-08 01:50:22,767 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:22,769 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:50:22,769 T0005: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:50:22,964 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2024-01-08 01:50:22,965 T0006: INFO  [D2-V2] admin@V2:~$ 
2024-01-08 01:50:22,968 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:22,970 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:50:22,970 T0006: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:50:27,775 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:27,976 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:28,186 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:28,383 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:28,799 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2024-01-08 01:50:28,799 T0005: INFO  [D1-V1] admin@V1:~$ 
2024-01-08 01:50:28,802 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:28,803 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:50:28,804 T0005: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:50:28,994 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2024-01-08 01:50:28,994 T0006: INFO  [D2-V2] admin@V2:~$ 
2024-01-08 01:50:28,996 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:28,998 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:50:28,998 T0006: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:50:33,809 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:34,004 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:34,216 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:34,411 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:34,877 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2024-01-08 01:50:34,877 T0005: INFO  [D1-V1] admin@V1:~$ 
2024-01-08 01:50:34,879 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:34,880 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:50:34,880 T0005: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:50:35,071 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2024-01-08 01:50:35,072 T0006: INFO  [D2-V2] admin@V2:~$ 
2024-01-08 01:50:35,074 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:35,076 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:50:35,076 T0006: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:50:39,886 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:40,082 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:40,293 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:40,489 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:40,903 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2024-01-08 01:50:40,903 T0005: INFO  [D1-V1] admin@V1:~$ 
2024-01-08 01:50:40,906 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:40,907 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:50:40,907 T0005: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:50:41,150 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2024-01-08 01:50:41,150 T0006: INFO  [D2-V2] admin@V2:~$ 
2024-01-08 01:50:41,153 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:41,155 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:50:41,155 T0006: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:50:45,913 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:46,160 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:46,320 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:46,567 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:46,980 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2024-01-08 01:50:46,981 T0005: INFO  [D1-V1] admin@V1:~$ 
2024-01-08 01:50:46,983 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:46,985 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:50:46,985 T0005: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:50:47,177 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2024-01-08 01:50:47,178 T0006: INFO  [D2-V2] admin@V2:~$ 
2024-01-08 01:50:47,181 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:47,183 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:50:47,183 T0006: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:50:51,990 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:52,186 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:52,397 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:52,593 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:53,006 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2024-01-08 01:50:53,006 T0005: INFO  [D1-V1] admin@V1:~$ 
2024-01-08 01:50:53,009 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:53,011 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:50:53,011 T0005: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:50:53,203 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2024-01-08 01:50:53,203 T0006: INFO  [D2-V2] admin@V2:~$ 
2024-01-08 01:50:53,206 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:53,207 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:50:53,208 T0006: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:50:58,014 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:58,210 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:58,421 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:58,617 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:59,032 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2024-01-08 01:50:59,032 T0005: INFO  [D1-V1] admin@V1:~$ 
2024-01-08 01:50:59,037 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:59,040 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:50:59,040 T0005: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:50:59,228 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2024-01-08 01:50:59,229 T0006: INFO  [D2-V2] admin@V2:~$ 
2024-01-08 01:50:59,231 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:50:59,233 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:50:59,233 T0006: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:51:04,046 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:51:04,238 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:51:04,455 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:51:04,645 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:51:05,115 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2024-01-08 01:51:05,115 T0005: INFO  [D1-V1] admin@V1:~$ 
2024-01-08 01:51:05,118 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:51:05,120 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:51:05,120 T0005: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:51:05,254 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2024-01-08 01:51:05,254 T0006: INFO  [D2-V2] admin@V2:~$ 
2024-01-08 01:51:05,257 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:51:05,259 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:51:05,259 T0006: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:51:10,126 T0005: ERROR [D1-V1] Failed to read hostname from vtysh - assuming sonic
2024-01-08 01:51:10,128 T0005: INFO  [D1-V1] Base Prompt: sonic
2024-01-08 01:51:10,129 T0005: DEBUG [D1-V1] Wait for system ready Ref: 866
2024-01-08 01:51:10,263 T0006: ERROR [D2-V2] Failed to read hostname from vtysh - assuming sonic
2024-01-08 01:51:10,265 T0006: INFO  [D2-V2] Base Prompt: sonic
2024-01-08 01:51:10,266 T0006: DEBUG [D2-V2] Wait for system ready Ref: 866
2024-01-08 01:51:10,535 T0005: INFO  [D1-V1] FCMD: sudo md5sum /etc/spytest/remote/spytest-helper.py
2024-01-08 01:51:10,671 T0006: INFO  [D2-V2] FCMD: sudo md5sum /etc/spytest/remote/spytest-helper.py
2024-01-08 01:51:10,791 T0005: INFO  [D1-V1] md5sum: /etc/spytest/remote/spytest-helper.py: No such file or directory
2024-01-08 01:51:10,791 T0005: INFO  [D1-V1] admin@V1:~$ 
2024-01-08 01:51:10,793 T0005: INFO  [D1-V1] MD5 different SRC: 4522abaafb8e29890a8377a810228525 DST: []
2024-01-08 01:51:10,794 T0005: INFO  [D1-V1] Trying to upload file '/repo/spytest/remote/spytest-helper.py'. attempt '1'
2024-01-08 01:51:10,795 T0005: INFO  [D1-V1] Transfer: SRC(SVR/VDI): /repo/spytest/remote/spytest-helper.py DST(V1): /tmp/spytest-helper.py
2024-01-08 01:51:10,796 T0005: ERROR [D1-V1] No mgmt IP
2024-01-08 01:51:10,797 T0005: INFO  [D1-V1] Doing SFTP transfer IP = None/YourPaSsWoRd/broadcom
2024-01-08 01:51:10,927 T0006: INFO  [D2-V2] md5sum: /etc/spytest/remote/spytest-helper.py: No such file or directory
2024-01-08 01:51:10,927 T0006: INFO  [D2-V2] admin@V2:~$ 
2024-01-08 01:51:10,931 T0006: INFO  [D2-V2] MD5 different SRC: 4522abaafb8e29890a8377a810228525 DST: []
2024-01-08 01:51:10,932 T0006: INFO  [D2-V2] Trying to upload file '/repo/spytest/remote/spytest-helper.py'. attempt '1'
2024-01-08 01:51:10,933 T0006: INFO  [D2-V2] Transfer: SRC(SVR/VDI): /repo/spytest/remote/spytest-helper.py DST(V2): /tmp/spytest-helper.py
2024-01-08 01:51:10,934 T0006: ERROR [D2-V2] No mgmt IP
2024-01-08 01:51:10,934 T0006: INFO  [D2-V2] Doing SFTP transfer IP = None/YourPaSsWoRd/broadcom
2024-01-08 01:51:10,981 T0005: INFO  [D1-V1] FCMD: sudo md5sum /tmp/spytest-helper.py
2024-01-08 01:51:11,120 T0006: INFO  [D2-V2] FCMD: sudo md5sum /tmp/spytest-helper.py
2024-01-08 01:51:11,237 T0005: INFO  [D1-V1] 4522abaafb8e29890a8377a810228525  /tmp/spytest-helper.py
2024-01-08 01:51:11,238 T0005: INFO  [D1-V1] admin@V1:~$ 
2024-01-08 01:51:11,240 T0005: INFO  [D1-V1] Trying to copy file to '/etc/spytest/remote/spytest-helper.py'. attempt '1'
2024-01-08 01:51:11,241 T0005: INFO  [D1-V1] SCMD: sudo mkdir -p /etc/spytest/remote && sudo cp -f /tmp/spytest-helper.py /etc/spytest/remote/spytest-helper.py
2024-01-08 01:51:11,376 T0006: INFO  [D2-V2] 4522abaafb8e29890a8377a810228525  /tmp/spytest-helper.py
2024-01-08 01:51:11,376 T0006: INFO  [D2-V2] admin@V2:~$ 
2024-01-08 01:51:11,377 T0006: INFO  [D2-V2] Trying to copy file to '/etc/spytest/remote/spytest-helper.py'. attempt '1'
2024-01-08 01:51:11,378 T0006: INFO  [D2-V2] SCMD: sudo mkdir -p /etc/spytest/remote && sudo cp -f /tmp/spytest-helper.py /etc/spytest/remote/spytest-helper.py
2024-01-08 01:51:13,848 T0005: INFO  [D1-V1] admin@V1:~$ 
2024-01-08 01:51:13,851 T0005: WARN  [D1-V1] Execute 'sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300' with timeout 600 sec -- TRY 1
2024-01-08 01:51:13,852 T0005: INFO  [D1-V1] SCMD: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2024-01-08 01:51:13,983 T0006: INFO  [D2-V2] admin@V2:~$ 
2024-01-08 01:51:13,985 T0006: WARN  [D2-V2] Execute 'sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300' with timeout 600 sec -- TRY 1
2024-01-08 01:51:13,985 T0006: INFO  [D2-V2] SCMD: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2024-01-08 01:51:17,681 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_python_traceback command: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2024-01-08 01:51:17,682 T0005: INFO  [D1-V1] 
2024-01-08 01:51:17,682 T0005: INFO  [D1-V1] Remote CMD: 'show platform summary'
2024-01-08 01:51:17,682 T0005: INFO  [D1-V1] Error: Failed to execute 'show platform summary' (out: '') (err: 'Traceback (most recent call last):
2024-01-08 01:51:17,682 T0005: INFO  [D1-V1]   File "/usr/local/bin/show", line 5, in <module>
2024-01-08 01:51:17,682 T0005: INFO  [D1-V1]     from show.main import cli
2024-01-08 01:51:17,682 T0005: INFO  [D1-V1]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2024-01-08 01:51:17,682 T0005: INFO  [D1-V1]     if is_gearbox_configured():
2024-01-08 01:51:17,682 T0005: INFO  [D1-V1]        ^^^^^^^^^^^^^^^^^^^^^^^
2024-01-08 01:51:17,682 T0005: INFO  [D1-V1]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2024-01-08 01:51:17,683 T0005: INFO  [D1-V1]     app_db.connect(app_db.APPL_DB)
2024-01-08 01:51:17,683 T0005: INFO  [D1-V1]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2024-01-08 01:51:17,683 T0005: INFO  [D1-V1]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2024-01-08 01:51:17,683 T0005: INFO  [D1-V1]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-08 01:51:17,683 T0005: INFO  [D1-V1] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2024-01-08 01:51:17,683 T0005: INFO  [D1-V1] 
2024-01-08 01:51:17,683 T0005: INFO  [D1-V1] Remote CMD: 'cat /usr/share/sonic/device/None/None/port_config.ini | tail -1'
2024-01-08 01:51:17,683 T0005: INFO  [D1-V1] Remote CMD: 'sudo show interfaces status '
2024-01-08 01:51:17,683 T0005: INFO  [D1-V1] Error: Failed to execute 'sudo show interfaces status ' (out: '') (err: 'Traceback (most recent call last):
2024-01-08 01:51:17,683 T0005: INFO  [D1-V1]   File "/usr/local/bin/show", line 5, in <module>
2024-01-08 01:51:17,683 T0005: INFO  [D1-V1]     from show.main import cli
2024-01-08 01:51:17,683 T0005: INFO  [D1-V1]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2024-01-08 01:51:17,683 T0005: INFO  [D1-V1]     if is_gearbox_configured():
2024-01-08 01:51:17,683 T0005: INFO  [D1-V1]        ^^^^^^^^^^^^^^^^^^^^^^^
2024-01-08 01:51:17,683 T0005: INFO  [D1-V1]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2024-01-08 01:51:17,684 T0005: INFO  [D1-V1]     app_db.connect(app_db.APPL_DB)
2024-01-08 01:51:17,684 T0005: INFO  [D1-V1]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2024-01-08 01:51:17,684 T0005: INFO  [D1-V1]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2024-01-08 01:51:17,684 T0005: INFO  [D1-V1]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-08 01:51:17,684 T0005: INFO  [D1-V1] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2024-01-08 01:51:17,684 T0005: INFO  [D1-V1] 
2024-01-08 01:51:17,684 T0005: INFO  [D1-V1] admin@V1:~$ 
2024-01-08 01:51:17,684 T0005: ERROR [D1-V1] Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2024-01-08 01:51:17,817 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_python_traceback command: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2024-01-08 01:51:17,818 T0006: INFO  [D2-V2] 
2024-01-08 01:51:17,818 T0006: INFO  [D2-V2] Remote CMD: 'show platform summary'
2024-01-08 01:51:17,818 T0006: INFO  [D2-V2] Error: Failed to execute 'show platform summary' (out: '') (err: 'Traceback (most recent call last):
2024-01-08 01:51:17,818 T0006: INFO  [D2-V2]   File "/usr/local/bin/show", line 5, in <module>
2024-01-08 01:51:17,818 T0006: INFO  [D2-V2]     from show.main import cli
2024-01-08 01:51:17,819 T0006: INFO  [D2-V2]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2024-01-08 01:51:17,819 T0006: INFO  [D2-V2]     if is_gearbox_configured():
2024-01-08 01:51:17,819 T0006: INFO  [D2-V2]        ^^^^^^^^^^^^^^^^^^^^^^^
2024-01-08 01:51:17,819 T0006: INFO  [D2-V2]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2024-01-08 01:51:17,819 T0006: INFO  [D2-V2]     app_db.connect(app_db.APPL_DB)
2024-01-08 01:51:17,819 T0006: INFO  [D2-V2]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2024-01-08 01:51:17,819 T0006: INFO  [D2-V2]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2024-01-08 01:51:17,819 T0006: INFO  [D2-V2]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-08 01:51:17,820 T0006: INFO  [D2-V2] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2024-01-08 01:51:17,820 T0006: INFO  [D2-V2] 
2024-01-08 01:51:17,820 T0006: INFO  [D2-V2] Remote CMD: 'cat /usr/share/sonic/device/None/None/port_config.ini | tail -1'
2024-01-08 01:51:17,820 T0006: INFO  [D2-V2] Remote CMD: 'sudo show interfaces status '
2024-01-08 01:51:17,820 T0006: INFO  [D2-V2] Error: Failed to execute 'sudo show interfaces status ' (out: '') (err: 'Traceback (most recent call last):
2024-01-08 01:51:17,820 T0006: INFO  [D2-V2]   File "/usr/local/bin/show", line 5, in <module>
2024-01-08 01:51:17,820 T0006: INFO  [D2-V2]     from show.main import cli
2024-01-08 01:51:17,820 T0006: INFO  [D2-V2]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2024-01-08 01:51:17,821 T0006: INFO  [D2-V2]     if is_gearbox_configured():
2024-01-08 01:51:17,821 T0006: INFO  [D2-V2]        ^^^^^^^^^^^^^^^^^^^^^^^
2024-01-08 01:51:17,821 T0006: INFO  [D2-V2]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2024-01-08 01:51:17,821 T0006: INFO  [D2-V2]     app_db.connect(app_db.APPL_DB)
2024-01-08 01:51:17,821 T0006: INFO  [D2-V2]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2024-01-08 01:51:17,821 T0006: INFO  [D2-V2]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2024-01-08 01:51:17,821 T0006: INFO  [D2-V2]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-08 01:51:17,821 T0006: INFO  [D2-V2] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2024-01-08 01:51:17,822 T0006: INFO  [D2-V2] 
2024-01-08 01:51:17,822 T0006: INFO  [D2-V2] admin@V2:~$ 
2024-01-08 01:51:17,822 T0006: ERROR [D2-V2] Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2024-01-08 01:51:17,823 T0004: ERROR exception in thread: Traceback (most recent call last):
  File "/repo/utilities/parallel.py", line 159, in _thread_func
    retvals[index] = func(*args, **kwargs)
  File "/repo/spytest/net.py", line 1064, in connect_to_device
    show_ver_output = self.connect_to_device_real(access, retry, recon, recover)
  File "/repo/spytest/net.py", line 1290, in connect_to_device_real
    self.do_common_init(devname, phase=0, max_ready_wait=max_ready_wait)
  File "/repo/spytest/net.py", line 866, in do_common_init
    sys_status = self.wa.wait_system_status(devname, max_time=max_ready_wait)
  File "/repo/spytest/framework.py", line 1616, in wait_system_status
    return self._wait_for_ports(dut, max_time)
  File "/repo/spytest/framework.py", line 1605, in _wait_for_ports
    return self.net.apply_remote(dut, "wait-for-ports", [max_time])
  File "/repo/spytest/net.py", line 4523, in apply_remote
    raise ValueError(msg)
ValueError: Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  

2024-01-08 01:51:17,823 T0004: ERROR exception in thread: Traceback (most recent call last):
  File "/repo/utilities/parallel.py", line 159, in _thread_func
    retvals[index] = func(*args, **kwargs)
  File "/repo/spytest/net.py", line 1064, in connect_to_device
    show_ver_output = self.connect_to_device_real(access, retry, recon, recover)
  File "/repo/spytest/net.py", line 1290, in connect_to_device_real
    self.do_common_init(devname, phase=0, max_ready_wait=max_ready_wait)
  File "/repo/spytest/net.py", line 866, in do_common_init
    sys_status = self.wa.wait_system_status(devname, max_time=max_ready_wait)
  File "/repo/spytest/framework.py", line 1616, in wait_system_status
    return self._wait_for_ports(dut, max_time)
  File "/repo/spytest/framework.py", line 1605, in _wait_for_ports
    return self.net.apply_remote(dut, "wait-for-ports", [max_time])
  File "/repo/spytest/net.py", line 4523, in apply_remote
    raise ValueError(msg)
ValueError: Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  

2024-01-08 01:51:17,824 T0004: ERROR [D1-V1] Failed to connect to device
2024-01-08 01:51:17,825 T0004: ERROR [D2-V2] Failed to connect to device
2024-01-08 01:51:17,826 T0000: ERROR Failed to connect (['V1', 'V2'])
2024-01-08 01:51:17,826 T0000: INFO  --FINISH--RUN--4 @559
