#,Module,TestFunction,Result,TimeTaken,ExecutedOn,Syslogs,FCLI,TSSH,DCNT,Description,Devices,KnownIssue,Doc
1,switching/test_vlan.py,,,0:00:40,2024-01-05 01:07:23,0,1,0,2,Module Prolog,"V3, V4",,
2,switching/test_vlan.py,test_ft_add_unknownvlan_interface,Pass,0:00:10,2024-01-05 01:07:26,0,1,0,2,Test case passed,"V3, V4",,verify that DUT should not assign unknown pvid
3,switching/test_vlan.py,test_ft_vlan_delete_with_member,Pass,0:00:15,2024-01-05 01:07:41,0,1,0,2,Test case passed,"V3, V4",,Verify that user is not able to delete a valn till its members are deleted
4,switching/test_vlan.py,test_ft_vlan_trunk_tagged,Pass,0:01:28,2024-01-05 01:09:09,0,1,0,2,Test case passed,"V3, V4",,Verify that over vlan trunk tagged packets received and be sent out with tag or without tag determined by traffic received from TGen.
5,switching/test_vlan.py,test_ft_vlan_save_config_warm_and_fast_reboot,ScriptError,0:12:10,2024-01-05 01:21:19,0,1,0,2,Exception TypeError 'NoneType' object is not subscriptable in file /apis/system/basic.py at line 1389,"V3, V4",,This script covers the below scenarios ft_max_vlan_save_reload	    Verify the save and reload functionality with max vlan configuration. ft_max_vlan_fast_reload	    Verify the max vlan configuration is retained after fast-reboot. FtOpSoSwVlFn026	            Verify that VLAN is present and traffic is not disturbed during and after warm reboot FtOpSoSysFRFn005            Verify the Fast-Reboot must disrupt control plane not more than 90 seconds (from sonic test suite -configuration tests) ft_reboot_fdb_fast_reboot   Verify that the FDB entry is retained after fast reboot.
6,switching/test_vlan.py,,,0:00:28,2024-01-05 01:21:47,0,1,0,2,Module Epilog,"V3, V4",,
7,system/test_ssh.py,,,0:03:10,2024-01-05 01:27:34,0,1,0,2,Module Prolog,"V3, V4",,
8,system/test_ssh.py,test_ft_ssh_service_disable,Pass,0:00:09,2024-01-05 01:27:37,0,1,0,2,Test case passed,"V3, V4",,
9,system/test_ssh.py,test_ft_ssh_add_user_verify,Fail,0:10:27,2024-01-05 01:38:04,0,1,0,2,Test case Failed.,"V3, V4",,
10,system/test_ssh.py,test_ft_verify_logs_at_the_time_of_ssh_login_success,Pass,0:00:26,2024-01-05 01:38:29,0,1,0,2,Test case passed,"V3, V4",,"ceta-sonic-67575: Verify that on successful ssh login, error logs are generated"
11,system/test_ssh.py,,,0:00:53,2024-01-05 01:39:21,0,1,0,2,Module Epilog,"V3, V4",,
