#,Module,Function,Result,Test Time,Helper Time,CMD Time,TG Time,Wait,TGWait,PROMPT NFOUND,TECH SUPPORT,Description
1,switching/test_portchannel.py,test_ft_portchannel_with_vlan_variations,,0:00:29,0:00:00.000,0:00:17.866,0:00:00.000,0:00:00,0:00:00,0,0,Module Configuration
2,switching/test_portchannel.py,test_ft_portchannel_with_vlan_variations,Pass,0:00:36,0:00:00.000,0:00:23.688,0:00:00.000,0:00:12,0:00:00,0,0,Test case passed
3,switching/test_portchannel.py,test_ft_verify_min_links_functionality_by_flapping_all_member_ports_007,Pass,0:00:21,0:00:00.000,0:00:10.750,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
4,system/test_lldp.py,test_ft_lldp_LocManAddrLen,Fail,0:00:00,0:00:36.481,0:00:48.342,0:00:00.000,0:00:30,0:00:00,0,0,module configuration failed. LLDP neighbors information is not found after polling @5445
5,system/test_lldp.py,test_ft_lldp_LocManAddrlfld,Fail,0:00:00,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,module configuration failed. LLDP neighbors information is not found after polling @5445
6,system/test_lldp.py,test_ft_lldp_LocManAddrEntry,Fail,0:00:00,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,module configuration failed. LLDP neighbors information is not found after polling @5445
7,system/test_lldp.py,test_ft_lldp_ConfigManAddrEntry,Fail,0:00:00,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,module configuration failed. LLDP neighbors information is not found after polling @5445
8,system/test_lldp.py,test_ft_lldp_lldplocportid,Fail,0:00:00,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,module configuration failed. LLDP neighbors information is not found after polling @5445
9,system/test_lldp.py,test_ft_lldp_lldplocsysname,Fail,0:00:00,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,module configuration failed. LLDP neighbors information is not found after polling @5445
10,system/test_lldp.py,test_ft_lldp_lldplocsysdesc,Fail,0:00:00,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,module configuration failed. LLDP neighbors information is not found after polling @5445
11,system/test_lldp.py,test_ft_lldp_rem_man_addr_table,Fail,0:00:00,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,module configuration failed. LLDP neighbors information is not found after polling @5445
12,system/test_lldp.py,test_ft_lldp_non_default_config,Fail,0:00:00,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,module configuration failed. LLDP neighbors information is not found after polling @5445
13,system/test_lldp.py,test_ft_lldp_docker_restart,Fail,0:00:00,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,module configuration failed. LLDP neighbors information is not found after polling @5445
14,system/test_lldp.py,test_lldp_verify_counters,Fail,0:00:00,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,module configuration failed. LLDP neighbors information is not found after polling @5445
15,system/test_lldp.py,test_ft_lldp_with_remote_server,Fail,0:00:00,0:00:00.000,0:00:00.000,0:00:00.000,0:00:00,0:00:00,0,0,module configuration failed. LLDP neighbors information is not found after polling @5445
16,system/test_ssh.py,test_ft_ssh_service_disable,,0:00:47,0:00:36.503,0:00:18.641,0:00:00.000,0:00:00,0:00:00,0,0,Module Configuration
17,system/test_ssh.py,test_ft_ssh_service_disable,Pass,0:00:08,0:00:00.000,0:00:00.671,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
18,system/test_ssh.py,test_ft_ssh_add_user_verify,ScriptError,0:02:40,0:00:00.000,0:00:23.800,0:00:00.000,0:00:00,0:00:00,0,0,Exception SPyTestCmdException Command Exception: sshpass -p 'YourPaSsWoRd' ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ConnectTimeout=30 admin@2.2.3.1 sudo show vlan config in file /spytest/net.py at line 1636
19,system/test_ssh.py,test_ft_verify_logs_at_the_time_of_ssh_login_success,Pass,0:00:22,0:00:00.000,0:00:05.135,0:00:00.000,0:00:00,0:00:00,0,0,Test case passed
20,system/test_interface.py,test_ft_port_fn_verify_shut_noshut,,0:02:47,0:02:06.616,0:00:25.178,0:00:00.000,0:00:15,0:00:00,0,0,Module Configuration
21,system/test_interface.py,test_ft_port_fn_verify_shut_noshut,Fail,0:01:55,0:00:56.079,0:00:32.557,0:00:00.000,0:00:00,0:00:00,0,0,interface is down on DUT ['Ethernet16']
