2023-12-25 00:53:38,415 T0000: NOTICE WORKER = gw2
2023-12-25 00:53:38,415 T0000: NOTICE using testbed file /data/work/logs/docker-master-440433-l3/testbed_1_2_1.yaml
2023-12-25 00:53:38,415 T0000: NOTICE Execution Start Time: 2023-12-25 00:53:38.413451
2023-12-25 00:53:38,415 T0000: NOTICE LOGS PATH: /data/work/logs/docker-master-440433-l3/gw2
2023-12-25 00:53:38,928 T0000: NOTICE VERSION: UNKNOWN UNKNOWN UNKNOWN
2023-12-25 00:53:38,928 T0000: NOTICE HOST: sonicmgmtmaster MEM: 376gb 32.5%
2023-12-25 00:53:38,928 T0000: NOTICE ROOT_PATH: /repo
2023-12-25 00:53:38,928 T0000: NOTICE Python: 3.8.10
2023-12-25 00:53:38,928 T0000: NOTICE Topology unknown: D1T1:4,D1D2:6,D2T1:4
2023-12-25 00:53:38,928 T0000: DEBUG 
SUITE ARGS: --load-image none --max-time module 9000 --max-time function 5400 --max-time session 3600 --logs-level=debug --topology-check=function --env SPYTEST_TESTBED_IGNORE_CONSTRAINTS TG,TGCARD,TGSPEED,CHIP,MODEL --noop --env SPYTEST_RESET_CONSOLES 0 --noop --env SPYTEST_ONREBOOT_RENEW_MGMT_IP 1 --noop --env SPYTEST_RECOVERY_CR_PER_CMD_POST_OP 1 --noop --env SPYTEST_BATCH_POLL_STATUS_TIME 300 --noop --env SPYTEST_BATCH_DEAD_NODE_MAX_TIME 7200 --noop --breakout-mode none --env SPYTEST_SHUTDOWN_FREE_PORTS 1 --env SPYTEST_HOOKS_BREAKOUT_UITYPE click --env SPYTEST_ONREBOOT_RENEW_MGMT_IP 0 --env SPYTEST_VERIFY_CSV_MIN_TOPOLOGY 1 --env SPYTEST_CMD_FAIL_RESULT_SUPPORT 0 --env SPYTEST_ROUTING_CONFIG_MODE split --env SPYTEST_CLEAR_DEVICE_METADATA_BGP_ASN 1 --env SPYTEST_TEXTFSM_USE_BUNDLED_PARSER 1 --feature-group master --ifname-type native --feature-disable bcmcmd --feature-disable warm-reboot --save config-db module --tclist-csv TestBGPConfed.test_confed_route_distribution_with_rmap,TestBGPConfed.test_ipv6_confed_route_distribution,TestBGPConfed.test_ipv6_confed_with_rr,TestBGPIPvxRouteAdvertisementFilter.test_bgp_ebgp4_nbr_authentication,TestBGPIPvxRouteAdvertisementFilter.test_bgp_ebgp4_nbr_update_source,TestBGPIPvxRouteAdvertisementFilter.test_bgp_route_map_with_community,TestBGPIPvxRouteAdvertisementFilter.test_default_originate_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_distribute_list_in_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_distribute_list_in_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_filter_list_in_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_filter_list_in_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_filter_list_out_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_prefix_list_out_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_prefix_list_out_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_route_aggregate_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_route_map_in_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_route_map_in_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_static_blackhole_rt_redistribute_with_routemap_ipv6,TestBGPL3Lag.test_ft_bgp_l3lag_peer_traffic_check,TestBGPRif.test_bgp_route_aggregation_4byteASN,TestBGPRif.test_ft_bgp_clear,TestBGPRif.test_ft_bgp_graceful_restart_and_aware_routers,TestBGPRif.test_ft_bgp_peer_traffic_check,TestBGPRif.test_ft_bgp_rmap,TestBGPRif.test_ft_bgp_v4_dyn_nbr,TestBGPRif.test_ft_bgp_v6_dyn_nbr,TestBGPRif.test_ft_bgp_v6_link_local_bgp,TestBGPRrTraffic.test_ft_bgp6_rr_traffic_check,TestBGPVeLag.test_ft_bgp_clear,TestBGPVeLag.test_ft_bgp_peer_traffic_check,test_VrfFun001_06,test_VrfFun_05_50,test_VrfFun_10_12_14,test_VrfFun_20_24_25_32_33_44_45,test_VrfFun_26_27,test_cli_validation_bgp_router_config,test_cli_validation_ip_address,test_ft_arp_dynamic_renew_traffic_test,test_ft_bgp_ebgp_community_map,test_ft_bgp_ibgp_RR_Loop,test_ft_ip6_static_route_traffic_forward_blackhole,test_ft_ip_static_ip_on_mgmt_intrf,test_ft_ip_static_route_traffic_forward,test_ft_ip_v4_v6_L2_L3_translation,test_ft_ipv6_neighbor_entry,test_ft_l3_performance_enhancements_v4_route_intstall_withdraw,test_ft_nat_docker_restart,test_ft_ping_v4_v6_after_ip_change_pc,test_ft_ping_v4_v6_vlan,test_ft_qos_config_mgmt_verifying_config_with_save_reboot,test_ft_sflow_max_sflow_collector_config,test_ft_sflow_sampling_v6_sFlow_collector,test_ft_system_config_mgmt_verifying_config_with_save_reboot_sflow,test_ft_verify_interfaces_order,test_l2_to_l3_port,test_l3_v4_route_po_1,test_vrf_bgp,test_vrf_reload,test_vrf_route_leak,test_vrf_scale,TestBGPRif.test_ft_bgp_ipv4_no_route_aggregation_for_exact_prefix_match,TestBGPRif.test_ft_bgp_ipv4_route_aggregation_atomic_aggregate_without_as_set,TestBGPRif.test_ft_bgp_ipv6_route_aggregation_with_as_set,TestBGPRif.test_ft_bgp_v4_max_dyn_nbr,TestBGPIPvxRouteAdvertisementFilter.test_redistribute_connected_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_redistribute_static_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_redistribute_connected_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_redistribute_static_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_default_originate_ipv6,test_spytest_infra_first,test_spytest_infra_second,test_spytest_infra_last --noop

2023-12-25 00:53:38,928 T0000: NOTICE ARGS: --logs-level debug --results-prefix=results --get-tech-support none --fetch-core-files none --syslog-check none --save config-db module --topology-check module --logs-path logs/2023-12-25-00-51-08 --continue-on-collection-errors --max-time session 0 --max-time module 0 --max-time function 0 --noop --tryssh=0 --testbed-file testbed.yaml --env SPYTEST_RPS_DEBUG 0 --tclist-bucket 1,2,4 --test-suite community-vs-l3 --email rama.kristipati@broadcom.com --env SPYTEST_SCAPY_DBG_LVL 2 --noop --env SPYTEST_EMAIL_FROM SPyTest-VSNet@broadcom.com --noop --logs-path logs/docker-master-440433-l3 --env SPYTEST_EMAIL_BODY_PREFIX http://10.193.81.56:8080/sonic_mgmt_master/work/logs/docker-master-440433-l3/dashboard.html --email-subject-nargs VSNet-sonic_mgmt_master-DOCKER-L3-{{bldver}} : {{passrate}}: {{pass_cnt}}/{{executed}} docker-master-440433-l3 --noop --feature-group master
2023-12-25 00:53:39,579 T0000: DEBUG 'errors' not set in properties for V3 assuming 'default'
2023-12-25 00:53:39,579 T0000: DEBUG 'errors' not set in properties for V4 assuming 'default'
2023-12-25 00:53:39,579 T0000: INFO  TGEN-IP 127.0.0.1
2023-12-25 00:53:39,579 T0000: WARN  Registering Topology
2023-12-25 00:53:39,601 T0000: INFO  Connecting all devices
2023-12-25 00:53:39,602 T0000: INFO  Loading scapy:1.0 127.0.0.1 Ports: ['1/9', '1/10', '1/11', '1/12', '1/13', '1/14', '1/15', '1/16'] skip: False
2023-12-25 00:53:40,093 T0005: INFO  [D1-V3] Connecting to device (V3): sonic_ssh: 172.18.0.4:22 ..
2023-12-25 00:53:40,093 T0005: INFO  [D1-V3] TRY Authentication: 172.18.0.4:22 admin YourPaSsWoRd
2023-12-25 00:53:40,099 T0006: INFO  [D2-V4] Connecting to device (V4): sonic_ssh: 172.18.0.5:22 ..
2023-12-25 00:53:40,100 T0006: INFO  [D2-V4] TRY Authentication: 172.18.0.5:22 admin YourPaSsWoRd
2023-12-25 00:53:40,614 T0000: INFO  TG Scapy Init
2023-12-25 00:53:40,615 T0000: INFO  TG Base Init skip: False
2023-12-25 00:53:40,625 T0000: INFO  TG Scapy Connect 127.0.0.1:8009
2023-12-25 00:53:40,740 T0000: INFO  Server Logs Path /data/work/scapy-tgen/logs/current/inst-2023_12_25_00_53_40_654141/gw2/default.log
2023-12-25 00:53:40,747 T0000: DEBUG REQ: tg_connect(port_list=['1/9', '1/10', '1/11', '1/12', '1/13', '1/14', '1/15', '1/16'])
2023-12-25 00:53:45,300 T0006: DEBUG [D2-V4] Connected ...
2023-12-25 00:53:45,305 T0005: DEBUG [D1-V3] Connected ...
2023-12-25 00:53:46,133 T0005: INFO  [D1-V3] Prompt at the connection start: 'admin@V3:~$' 
2023-12-25 00:53:46,135 T0005: AUDIT [D1-V3] ['export TMOUT=0', 'stty cols 5000', 'uptime']
2023-12-25 00:53:46,135 T0006: INFO  [D2-V4] Prompt at the connection start: 'admin@V4:~$' 
2023-12-25 00:53:46,136 T0006: AUDIT [D2-V4] ['export TMOUT=0', 'stty cols 5000', 'uptime']
2023-12-25 00:53:46,546 T0005: INFO  [D1-V3] FCMD: export TMOUT=0;stty cols 5000;uptime
2023-12-25 00:53:46,552 T0006: INFO  [D2-V4] FCMD: export TMOUT=0;stty cols 5000;uptime
2023-12-25 00:53:46,809 T0005: INFO  [D1-V3]  00:53:46 up 17 days,  1:55,  1 user,  load average: 3.84, 9.34, 8.63
2023-12-25 00:53:46,810 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-25 00:53:46,821 T0005: AUDIT [D1-V3] cat /proc/uptime
2023-12-25 00:53:46,824 T0006: INFO  [D2-V4]  00:53:46 up 17 days,  1:55,  1 user,  load average: 3.84, 9.34, 8.63
2023-12-25 00:53:46,824 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-25 00:53:46,826 T0006: AUDIT [D2-V4] cat /proc/uptime
2023-12-25 00:53:47,226 T0005: INFO  [D1-V3] FCMD: cat /proc/uptime
2023-12-25 00:53:47,232 T0006: INFO  [D2-V4] FCMD: cat /proc/uptime
2023-12-25 00:53:47,481 T0005: INFO  [D1-V3] 1475701.22 116430457.46
2023-12-25 00:53:47,482 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-25 00:53:47,484 T0005: INFO  [D1-V3] UPTIME: 1475701.22
2023-12-25 00:53:47,485 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:53:47,491 T0006: INFO  [D2-V4] 1475701.23 116430457.94
2023-12-25 00:53:47,491 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-25 00:53:47,493 T0006: INFO  [D2-V4] UPTIME: 1475701.23
2023-12-25 00:53:47,494 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:53:47,895 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:53:47,901 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:53:48,507 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-25 00:53:48,507 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-25 00:53:48,510 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:53:48,513 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-25 00:53:48,513 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-25 00:53:48,515 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:53:48,516 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:53:48,518 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:53:48,520 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:53:48,520 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:53:53,153 T0000: DEBUG RESP: tg_connect {"port_handle": {"1/9": "port-9", "1/10": "port-10", "1/11": "port-11", "1/12": "port-12", "1/13": "port-13", "1/14": "port-14", "1/15": "port-15", "1/16": "port-16"}, "status": 1}
2023-12-25 00:53:53,168 T0000: INFO  TG Connection: Success
2023-12-25 00:53:53,168 T0000: INFO  TG Connect...done
2023-12-25 00:53:53,522 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:53:53,526 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:53:53,929 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:53:53,935 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:53:54,543 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-25 00:53:54,543 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-25 00:53:54,546 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:53:54,548 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-25 00:53:54,549 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-25 00:53:54,551 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:53:54,551 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:53:54,553 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:53:54,555 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:53:54,556 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:53:59,557 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:53:59,561 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:53:59,965 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:53:59,971 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:00,579 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-25 00:54:00,579 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-25 00:54:00,583 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-25 00:54:00,583 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-25 00:54:00,586 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:00,588 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:00,590 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:54:00,591 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:54:00,592 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:54:00,593 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:54:05,596 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:05,598 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:06,011 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:06,017 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:06,627 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-25 00:54:06,627 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-25 00:54:06,630 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-25 00:54:06,630 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-25 00:54:06,632 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:06,634 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:06,636 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:54:06,636 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:54:06,637 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:54:06,637 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:54:11,641 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:11,642 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:12,053 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:12,059 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:12,669 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-25 00:54:12,669 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-25 00:54:12,672 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-25 00:54:12,672 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-25 00:54:12,675 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:12,677 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:12,679 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:54:12,679 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:54:12,680 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:54:12,681 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:54:17,685 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:17,686 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:18,098 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:18,104 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:18,764 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-25 00:54:18,764 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-25 00:54:18,767 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-25 00:54:18,767 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-25 00:54:18,770 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:18,772 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:18,773 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:54:18,774 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:54:18,775 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:54:18,775 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:54:23,777 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:23,781 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:24,184 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:24,191 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:24,795 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-25 00:54:24,795 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-25 00:54:24,798 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:24,800 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:54:24,800 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:54:24,803 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-25 00:54:24,804 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-25 00:54:24,806 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:24,808 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:54:24,808 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:54:29,805 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:29,814 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:30,212 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:30,220 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:30,822 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-25 00:54:30,823 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-25 00:54:30,825 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:30,827 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:54:30,827 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:54:30,830 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-25 00:54:30,830 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-25 00:54:30,832 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:30,834 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:54:30,834 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:54:35,833 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:35,840 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:36,240 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:36,247 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:36,851 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-25 00:54:36,851 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-25 00:54:36,853 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:36,855 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:54:36,855 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:54:36,857 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-25 00:54:36,858 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-25 00:54:36,860 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:36,863 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:54:36,863 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:54:41,861 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:41,869 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:42,268 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:42,277 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:42,880 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-25 00:54:42,880 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-25 00:54:42,883 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:42,885 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:54:42,885 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:54:42,888 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-25 00:54:42,888 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-25 00:54:42,891 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:42,893 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:54:42,893 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:54:47,889 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:47,898 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:48,296 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:48,305 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:48,906 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-25 00:54:48,906 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-25 00:54:48,909 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:48,911 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:54:48,911 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:54:48,915 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-25 00:54:48,915 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-25 00:54:48,917 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:48,920 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:54:48,920 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:54:53,917 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:53,926 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:54,324 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:54,333 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:54,934 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-25 00:54:54,935 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-25 00:54:54,937 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:54,938 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:54:54,938 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:54:54,995 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-25 00:54:54,995 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-25 00:54:54,998 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:55,000 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:54:55,000 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:54:59,941 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:00,004 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:00,348 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:00,414 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:00,958 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-25 00:55:00,958 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-25 00:55:00,961 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:00,963 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:55:00,963 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:55:01,024 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-25 00:55:01,024 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-25 00:55:01,026 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:01,028 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:55:01,029 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:55:05,969 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:06,034 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:06,376 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:06,441 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:06,987 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-25 00:55:06,987 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-25 00:55:06,989 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:06,991 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:55:06,991 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:55:07,051 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-25 00:55:07,051 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-25 00:55:07,053 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:07,054 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:55:07,054 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:55:11,997 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:12,059 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:12,404 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:12,467 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:13,014 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-25 00:55:13,014 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-25 00:55:13,017 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:13,019 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:55:13,019 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:55:13,078 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-25 00:55:13,078 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-25 00:55:13,080 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:13,082 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:55:13,083 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:55:18,025 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:18,085 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:18,432 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:18,491 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:19,042 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-25 00:55:19,044 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-25 00:55:19,047 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:19,048 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:55:19,049 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:55:19,102 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-25 00:55:19,102 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-25 00:55:19,104 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:19,106 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:55:19,106 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:55:24,054 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:24,112 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:24,462 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:24,519 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:25,072 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-25 00:55:25,072 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-25 00:55:25,075 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:25,077 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:55:25,077 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:55:25,130 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-25 00:55:25,130 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-25 00:55:25,133 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:25,135 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:55:25,135 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:55:30,081 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:30,140 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:30,489 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:30,546 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:31,097 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-25 00:55:31,097 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-25 00:55:31,099 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:31,100 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:55:31,100 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:55:31,253 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-25 00:55:31,254 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-25 00:55:31,255 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:31,257 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:55:31,257 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:55:36,105 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:36,260 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:36,515 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:36,667 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:37,178 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-25 00:55:37,178 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-25 00:55:37,181 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:37,183 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:55:37,183 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:55:37,378 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-25 00:55:37,378 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-25 00:55:37,383 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:37,386 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:55:37,386 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:55:42,185 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:42,389 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:42,591 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:42,797 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:43,354 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-25 00:55:43,356 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-25 00:55:43,359 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:43,362 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:55:43,362 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:55:43,459 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-25 00:55:43,459 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-25 00:55:43,461 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:43,462 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:55:43,462 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:55:48,369 T0006: ERROR [D2-V4] Failed to read hostname from vtysh - assuming sonic
2023-12-25 00:55:48,372 T0006: INFO  [D2-V4] Base Prompt: sonic
2023-12-25 00:55:48,373 T0006: DEBUG [D2-V4] Wait for system ready Ref: 866
2023-12-25 00:55:48,466 T0005: ERROR [D1-V3] Failed to read hostname from vtysh - assuming sonic
2023-12-25 00:55:48,468 T0005: INFO  [D1-V3] Base Prompt: sonic
2023-12-25 00:55:48,469 T0005: DEBUG [D1-V3] Wait for system ready Ref: 866
2023-12-25 00:55:48,779 T0006: INFO  [D2-V4] FCMD: sudo md5sum /etc/spytest/remote/spytest-helper.py
2023-12-25 00:55:48,874 T0005: INFO  [D1-V3] FCMD: sudo md5sum /etc/spytest/remote/spytest-helper.py
2023-12-25 00:55:49,035 T0006: INFO  [D2-V4] 4522abaafb8e29890a8377a810228525  /etc/spytest/remote/spytest-helper.py
2023-12-25 00:55:49,035 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-25 00:55:49,039 T0006: WARN  [D2-V4] Execute 'sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300' with timeout 600 sec -- TRY 1
2023-12-25 00:55:49,041 T0006: INFO  [D2-V4] SCMD: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-25 00:55:49,131 T0005: INFO  [D1-V3] 4522abaafb8e29890a8377a810228525  /etc/spytest/remote/spytest-helper.py
2023-12-25 00:55:49,131 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-25 00:55:49,134 T0005: WARN  [D1-V3] Execute 'sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300' with timeout 600 sec -- TRY 1
2023-12-25 00:55:49,135 T0005: INFO  [D1-V3] SCMD: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-25 00:55:51,664 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_python_traceback command: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-25 00:55:51,666 T0006: INFO  [D2-V4] 
2023-12-25 00:55:51,666 T0006: INFO  [D2-V4] Remote CMD: 'show platform summary'
2023-12-25 00:55:51,667 T0006: INFO  [D2-V4] Error: Failed to execute 'show platform summary' (out: '') (err: 'Traceback (most recent call last):
2023-12-25 00:55:51,667 T0006: INFO  [D2-V4]   File "/usr/local/bin/show", line 5, in <module>
2023-12-25 00:55:51,667 T0006: INFO  [D2-V4]     from show.main import cli
2023-12-25 00:55:51,667 T0006: INFO  [D2-V4]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2023-12-25 00:55:51,667 T0006: INFO  [D2-V4]     if is_gearbox_configured():
2023-12-25 00:55:51,667 T0006: INFO  [D2-V4]        ^^^^^^^^^^^^^^^^^^^^^^^
2023-12-25 00:55:51,668 T0006: INFO  [D2-V4]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2023-12-25 00:55:51,668 T0006: INFO  [D2-V4]     app_db.connect(app_db.APPL_DB)
2023-12-25 00:55:51,668 T0006: INFO  [D2-V4]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2023-12-25 00:55:51,668 T0006: INFO  [D2-V4]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2023-12-25 00:55:51,669 T0006: INFO  [D2-V4]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-25 00:55:51,669 T0006: INFO  [D2-V4] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2023-12-25 00:55:51,669 T0006: INFO  [D2-V4] 
2023-12-25 00:55:51,669 T0006: INFO  [D2-V4] Remote CMD: 'cat /usr/share/sonic/device/None/None/port_config.ini | tail -1'
2023-12-25 00:55:51,669 T0006: INFO  [D2-V4] Remote CMD: 'sudo show interfaces status '
2023-12-25 00:55:51,669 T0006: INFO  [D2-V4] Error: Failed to execute 'sudo show interfaces status ' (out: '') (err: 'Traceback (most recent call last):
2023-12-25 00:55:51,669 T0006: INFO  [D2-V4]   File "/usr/local/bin/show", line 5, in <module>
2023-12-25 00:55:51,669 T0006: INFO  [D2-V4]     from show.main import cli
2023-12-25 00:55:51,669 T0006: INFO  [D2-V4]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2023-12-25 00:55:51,669 T0006: INFO  [D2-V4]     if is_gearbox_configured():
2023-12-25 00:55:51,669 T0006: INFO  [D2-V4]        ^^^^^^^^^^^^^^^^^^^^^^^
2023-12-25 00:55:51,669 T0006: INFO  [D2-V4]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2023-12-25 00:55:51,669 T0006: INFO  [D2-V4]     app_db.connect(app_db.APPL_DB)
2023-12-25 00:55:51,669 T0006: INFO  [D2-V4]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2023-12-25 00:55:51,670 T0006: INFO  [D2-V4]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2023-12-25 00:55:51,670 T0006: INFO  [D2-V4]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-25 00:55:51,670 T0006: INFO  [D2-V4] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2023-12-25 00:55:51,670 T0006: INFO  [D2-V4] 
2023-12-25 00:55:51,670 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-25 00:55:51,670 T0006: ERROR [D2-V4] Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-25 00:55:52,963 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_python_traceback command: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-25 00:55:52,964 T0005: INFO  [D1-V3] 
2023-12-25 00:55:52,964 T0005: INFO  [D1-V3] Remote CMD: 'show platform summary'
2023-12-25 00:55:52,964 T0005: INFO  [D1-V3] Error: Failed to execute 'show platform summary' (out: '') (err: 'Traceback (most recent call last):
2023-12-25 00:55:52,965 T0005: INFO  [D1-V3]   File "/usr/local/bin/show", line 5, in <module>
2023-12-25 00:55:52,965 T0005: INFO  [D1-V3]     from show.main import cli
2023-12-25 00:55:52,965 T0005: INFO  [D1-V3]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2023-12-25 00:55:52,965 T0005: INFO  [D1-V3]     if is_gearbox_configured():
2023-12-25 00:55:52,965 T0005: INFO  [D1-V3]        ^^^^^^^^^^^^^^^^^^^^^^^
2023-12-25 00:55:52,965 T0005: INFO  [D1-V3]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2023-12-25 00:55:52,966 T0005: INFO  [D1-V3]     app_db.connect(app_db.APPL_DB)
2023-12-25 00:55:52,966 T0005: INFO  [D1-V3]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2023-12-25 00:55:52,966 T0005: INFO  [D1-V3]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2023-12-25 00:55:52,966 T0005: INFO  [D1-V3]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-25 00:55:52,966 T0005: INFO  [D1-V3] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2023-12-25 00:55:52,966 T0005: INFO  [D1-V3] 
2023-12-25 00:55:52,967 T0005: INFO  [D1-V3] Remote CMD: 'cat /usr/share/sonic/device/None/None/port_config.ini | tail -1'
2023-12-25 00:55:52,967 T0005: INFO  [D1-V3] Remote CMD: 'sudo show interfaces status '
2023-12-25 00:55:52,967 T0005: INFO  [D1-V3] Error: Failed to execute 'sudo show interfaces status ' (out: '') (err: 'Traceback (most recent call last):
2023-12-25 00:55:52,967 T0005: INFO  [D1-V3]   File "/usr/local/bin/show", line 5, in <module>
2023-12-25 00:55:52,967 T0005: INFO  [D1-V3]     from show.main import cli
2023-12-25 00:55:52,967 T0005: INFO  [D1-V3]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2023-12-25 00:55:52,967 T0005: INFO  [D1-V3]     if is_gearbox_configured():
2023-12-25 00:55:52,968 T0005: INFO  [D1-V3]        ^^^^^^^^^^^^^^^^^^^^^^^
2023-12-25 00:55:52,968 T0005: INFO  [D1-V3]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2023-12-25 00:55:52,968 T0005: INFO  [D1-V3]     app_db.connect(app_db.APPL_DB)
2023-12-25 00:55:52,968 T0005: INFO  [D1-V3]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2023-12-25 00:55:52,968 T0005: INFO  [D1-V3]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2023-12-25 00:55:52,968 T0005: INFO  [D1-V3]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-25 00:55:52,969 T0005: INFO  [D1-V3] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2023-12-25 00:55:52,969 T0005: INFO  [D1-V3] 
2023-12-25 00:55:52,969 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-25 00:55:52,970 T0005: ERROR [D1-V3] Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-25 00:55:52,970 T0004: ERROR exception in thread: Traceback (most recent call last):
  File "/repo/utilities/parallel.py", line 159, in _thread_func
    retvals[index] = func(*args, **kwargs)
  File "/repo/spytest/net.py", line 1064, in connect_to_device
    show_ver_output = self.connect_to_device_real(access, retry, recon, recover)
  File "/repo/spytest/net.py", line 1290, in connect_to_device_real
    self.do_common_init(devname, phase=0, max_ready_wait=max_ready_wait)
  File "/repo/spytest/net.py", line 866, in do_common_init
    sys_status = self.wa.wait_system_status(devname, max_time=max_ready_wait)
  File "/repo/spytest/framework.py", line 1616, in wait_system_status
    return self._wait_for_ports(dut, max_time)
  File "/repo/spytest/framework.py", line 1605, in _wait_for_ports
    return self.net.apply_remote(dut, "wait-for-ports", [max_time])
  File "/repo/spytest/net.py", line 4523, in apply_remote
    raise ValueError(msg)
ValueError: Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  

2023-12-25 00:55:52,971 T0004: ERROR exception in thread: Traceback (most recent call last):
  File "/repo/utilities/parallel.py", line 159, in _thread_func
    retvals[index] = func(*args, **kwargs)
  File "/repo/spytest/net.py", line 1064, in connect_to_device
    show_ver_output = self.connect_to_device_real(access, retry, recon, recover)
  File "/repo/spytest/net.py", line 1290, in connect_to_device_real
    self.do_common_init(devname, phase=0, max_ready_wait=max_ready_wait)
  File "/repo/spytest/net.py", line 866, in do_common_init
    sys_status = self.wa.wait_system_status(devname, max_time=max_ready_wait)
  File "/repo/spytest/framework.py", line 1616, in wait_system_status
    return self._wait_for_ports(dut, max_time)
  File "/repo/spytest/framework.py", line 1605, in _wait_for_ports
    return self.net.apply_remote(dut, "wait-for-ports", [max_time])
  File "/repo/spytest/net.py", line 4523, in apply_remote
    raise ValueError(msg)
ValueError: Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  

2023-12-25 00:55:52,972 T0004: ERROR [D1-V3] Failed to connect to device
2023-12-25 00:55:52,974 T0004: ERROR [D2-V4] Failed to connect to device
2023-12-25 00:55:52,975 T0000: ERROR Failed to connect (['V3', 'V4'])
2023-12-25 00:55:52,975 T0000: INFO  --FINISH--RUN--4 @559
